// life-assisitant-ui-desktop/src/components/finance/SummaryCards.tsx
/**
 * SummaryCards —— 收支页顶部数据块（桌面端 · spec-20260922-v2 · 01 §2 / §2.7）
 *
 * SYNC-FROM-MOBILE: life-assisitant-ui-mobile/src/components/finance/SummaryCards.vue
 * （两卡两面 / 三热区 / 边界态与移动端**同构**；周期与两面存**同一组 localStorage key**
 *   —— 01 §2.7「用户在一端选了另一段也跟着变」是期望行为，key 见 constants/finance.ts）
 *
 * 左块：本月收入 ⇄ 本月支出（块主体点击翻面）
 * 右块：剩余预算 ⇄ 月结余（翻面 + 标题里的「月/周/年」周期字独立热区，月→周→年 循环）
 * 四个数全部走 GET /finance/summary（服务端口径，修 S2/S3）。
 *
 * 边界态（01 §2.8）：加载 = 骨架无 spinner；失败 = `—` + 「加载失败 · 点击重试」；
 * 无 total 预算 = `—` + 「未设预算 · 去设置 ›」（onGotoBudget，不显示 ¥0）；结余负 = danger。
 * 桌面差异（01 §2.7）：周期字挂 Tooltip「点击切换周期」。
 */
import { useEffect } from 'react'
import { Tooltip } from '@douyinfe/semi-ui'
import { useFinanceStore } from '@/stores/finance'
import { MoneyText } from '@/components/finance/MoneyText'
import type { MoneyType } from '@/utils/money'

const CARD: React.CSSProperties = {
  flex: 1,
  minWidth: 0,
  height: 84,
  boxSizing: 'border-box',
  padding: '10px 16px',
  borderRadius: 'var(--radius-lg)',
  background: 'var(--color-bg-card)',
  border: '1px solid var(--color-border-light)',
  cursor: 'pointer',
  userSelect: 'none',
  overflow: 'hidden',
}
const TITLE: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 6,
  fontSize: 12,
  lineHeight: '16px',
  color: 'var(--color-text-secondary)',
  whiteSpace: 'nowrap',
}
const MAIN: React.CSSProperties = {
  fontSize: 22,
  fontWeight: 700,
  lineHeight: '30px',
  fontVariantNumeric: 'tabular-nums',
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
}
const SUB: React.CSSProperties = {
  fontSize: 12,
  lineHeight: '16px',
  color: 'var(--color-text-tertiary)',
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
}
const FLIP: React.CSSProperties = { fontSize: 12, color: 'var(--color-text-tertiary)' }
const PERIOD: React.CSSProperties = {
  color: 'var(--color-primary)',
  borderBottom: '1px dashed var(--color-primary)',
  lineHeight: '14px',
  padding: '0 1px',
  cursor: 'pointer',
}
const SK: React.CSSProperties = {
  display: 'block',
  borderRadius: 'var(--radius-sm)',
  background: 'var(--color-bg-hover)',
}

export function SummaryCards({ onGotoBudget }: { onGotoBudget?: () => void }) {
  const summary = useFinanceStore((s) => s.summary)
  const loading = useFinanceStore((s) => s.summaryLoading)
  const error = useFinanceStore((s) => s.summaryError)
  const period = useFinanceStore((s) => s.summaryPeriod)
  const cardLeft = useFinanceStore((s) => s.summaryCardLeft)
  const cardRight = useFinanceStore((s) => s.summaryCardRight)
  const fetchSummary = useFinanceStore((s) => s.fetchSummary)
  const cyclePeriod = useFinanceStore((s) => s.cycleSummaryPeriod)
  const flipLeft = useFinanceStore((s) => s.flipSummaryCardLeft)
  const flipRight = useFinanceStore((s) => s.flipSummaryCardRight)

  /** 进视图就拉一次（数字常新；翻面/切周期的刷新由 store 动作自己触发） */
  useEffect(() => {
    void fetchSummary()
  }, [fetchSummary])

  /* 三态（01 §2.8）：加载/首次无数据 = 骨架；失败 = 重试态；否则数据 */
  const phase: 'skeleton' | 'error' | 'data' =
    loading || !summary ? (error ? 'error' : 'skeleton') : 'data'

  const pShort = period === 'week' ? '周' : period === 'year' ? '年' : '月'
  const pPrefix = `今${pShort}`

  /* 左块（收入 face 带 +¥ 绿 / 支出 face 带 −¥(U+2212) 红；副行 = 另一面无符号）
     ⚠️ 数字一律交给 <MoneyText>（03 §2.2 #16）：遮罩态它自带中性色，
        会盖过父容器继承来的红/绿 ⇒ 不泄露正负 */
  const leftFace: MoneyType = cardLeft === 'income' ? 'income' : 'expense'
  const leftTitle = `${pPrefix}${cardLeft === 'income' ? '收入' : '支出'}`
  const leftMainValue = summary ? (cardLeft === 'income' ? summary.income : summary.expense) : 0
  const leftMainColor = summary
    ? cardLeft === 'income'
      ? 'var(--color-success-dark)'
      : 'var(--color-danger-dark)'
    : 'var(--color-text-primary)'
  const leftSubValue = summary ? (cardLeft === 'income' ? summary.expense : summary.income) : 0

  /* 右块 */
  const budgetEmpty = !!summary && summary.budget.count === 0
  const rightTitleA = (
      <>
        <span>剩余预算 ·</span>
        <Tooltip content="点击切换周期（月→周→年）">
          <span style={PERIOD} onClick={(e) => { e.stopPropagation(); cyclePeriod() }}>{pShort}</span>
        </Tooltip>
      </>
  )
  const rightTitleB = (
      <>
        <Tooltip content="点击切换周期（月→周→年）">
          <span style={PERIOD} onClick={(e) => { e.stopPropagation(); cyclePeriod() }}>{pShort}</span>
        </Tooltip>
        <span>结余</span>
      </>
  )
  /** null = 无 total 预算（渲染 `—`，不显示 ¥0，Q3） */
  let rightMainValue: number | null = null
  let rightSigned: MoneyType | '' = ''
  let rightMainColor = 'var(--color-text-primary)'
  let rightSubPrefix = ''
  let rightSubValue: number | null = null
  let rightSubText = ''
  let rightSubAction = false
  if (summary) {
    if (cardRight === 'budget') {
      if (budgetEmpty) {
        rightSubText = '未设预算 · 去设置 ›'
        rightSubAction = true
      } else {
        rightMainValue = Math.abs(summary.budget.remaining)
        rightSigned = summary.budget.remaining < 0 ? 'expense' : ''
        if (summary.budget.remaining < 0) rightMainColor = 'var(--color-danger-dark)'
        rightSubPrefix = `${pShort}结余 `
        rightSubValue = summary.net
      }
    } else {
      rightMainValue = Math.abs(summary.net)
      rightSigned = summary.net >= 0 ? 'income' : 'expense'
      rightMainColor = summary.net >= 0 ? 'var(--color-success-dark)' : 'var(--color-danger-dark)'
      if (budgetEmpty) {
        rightSubText = '剩余预算 —'
      } else {
        rightSubPrefix = '剩余预算 '
        rightSubValue = summary.budget.remaining
      }
    }
  }

  const onLeftBody = () => {
    if (phase === 'error') void fetchSummary()
    else if (phase === 'data') flipLeft()
  }
  const onRightBody = () => {
    if (phase === 'error') void fetchSummary()
    else if (phase === 'data') flipRight()
  }

  return (
    <div style={{ display: 'flex', gap: 12, marginBottom: 12 }}>
      {/* ==================== 左块 ==================== */}
      <div style={CARD} onClick={onLeftBody} title={phase === 'data' ? '点击切换 收入 / 支出' : undefined}>
        {phase === 'data' ? (
          <>
            <div style={TITLE}><span>{leftTitle}</span><span style={FLIP}>⇄</span></div>
            <div style={{ ...MAIN, color: leftMainColor }}>
              <MoneyText value={leftMainValue} signed={leftFace} />
            </div>
            <div style={SUB}>
              {cardLeft === 'income' ? '支出 ' : '收入 '}<MoneyText value={leftSubValue} />
            </div>
          </>
        ) : phase === 'error' ? (
          <>
            <div style={TITLE}><span>数据</span></div>
            <div style={MAIN}>—</div>
            <div style={SUB}>加载失败 · 点击重试</div>
          </>
        ) : (
          <>
            <span style={{ ...SK, width: '40%', height: 12 }} />
            <span style={{ ...SK, width: '62%', height: 22, display: 'block', marginTop: 6 }} />
          </>
        )}
      </div>

      {/* ==================== 右块 ==================== */}
      <div style={CARD} onClick={onRightBody} title={phase === 'data' ? '点击切换 预算 / 结余' : undefined}>
        {phase === 'data' ? (
          <>
            <div style={TITLE}>
              {cardRight === 'budget' ? rightTitleA : rightTitleB}
              <span style={FLIP}>⇄</span>
            </div>
            <div style={{ ...MAIN, color: rightMainColor }}>
              {rightMainValue === null ? '—' : <MoneyText value={rightMainValue} signed={rightSigned} />}
            </div>
            <div
              style={{ ...SUB, ...(rightSubAction ? { color: 'var(--color-primary)', cursor: 'pointer' } : null) }}
              onClick={
                rightSubAction
                  ? (e) => { e.stopPropagation(); onGotoBudget?.() }
                  : undefined
              }
            >
              {rightSubValue === null
                ? rightSubText
                : <>{rightSubPrefix}<MoneyText value={rightSubValue} /></>}
            </div>
          </>
        ) : phase === 'error' ? (
          <>
            <div style={TITLE}>
              <span>数据 ·</span>
              <span style={PERIOD} onClick={(e) => { e.stopPropagation(); cyclePeriod() }}>{pShort}</span>
            </div>
            <div style={MAIN}>—</div>
            <div style={SUB}>加载失败 · 点击重试</div>
          </>
        ) : (
          <>
            <span style={{ ...SK, width: '46%', height: 12 }} />
            <span style={{ ...SK, width: '62%', height: 22, display: 'block', marginTop: 6 }} />
          </>
        )}
      </div>
    </div>
  )
}

export default SummaryCards

// life-assisitant-ui-mobile/src/components/finance/SummaryCards.vue
<!--
  流水页顶部数据块（spec-20260922-v2 · 01 §2）

  两卡各两面（块主体点击翻面，副行永远显示另一面 ⇒ 不点击也能看到两个数）：
    左块：本月收入 ⇄ 本月支出
    右块：剩余预算 ⇄ 月结余（标题里的周期字「月/周/年」= 独立热区，点击 月→周→年 循环）

  四个数**全部来自服务端** GET /finance/summary（修 S2「按已加载记录统计」、S3「预算混算」）。
  周期与两态存 localStorage（`constants/finance.ts` 三把 key，D10/D11），两端同源。

  边界态（01 §2.8，逐条对应模板分支）：
    - 加载中 / 首次未有数据 → 骨架块（--color-bg-hover 占位，无 spinner、无副行）
    - 请求失败 → 主值 `—` + 副行「加载失败 · 点击重试」，**不弹 toast**
    - 无 scope=total 预算 → 预算面主值 `—` + 副行「未设预算 · 去设置 ›」（emit goto-budget），**不显示 ¥0**
    - 结余为负 → danger；收入 success / 支出 danger（记账惯例，utils/money.ts 同一套符号）
-->
<template>
  <div class="summary-cards">
    <!-- ==================== 左块：收入 ⇄ 支出 ==================== -->
    <div class="sum-card" @click="onLeftBody">
      <template v-if="phase === 'data'">
        <div class="sum-title">
          <span>{{ periodPrefix }}{{ leftFace === 'income' ? '收入' : '支出' }}</span>
          <van-icon name="replay" class="sum-flip" />
        </div>
        <!-- 正负色 class 挂**父容器**（继承）；MoneyText 遮罩态的中性色会盖过继承
             ⇒ 遮罩时不泄露「这是负数」。切勿把 color 直接绑到 MoneyText 上。 -->
        <div class="sum-main" :class="leftFace === 'income' ? 'is-up' : 'is-down'">
          <MoneyText :value="leftMainValue" :signed="leftFace" />
        </div>
        <div class="sum-sub">{{ leftFace === 'income' ? '支出 ' : '收入 ' }}<MoneyText :value="leftSubValue" /></div>
      </template>
      <div v-else-if="phase === 'error'" class="sum-fill">
        <div class="sum-title"><span>数据</span></div>
        <div class="sum-main">—</div>
        <div class="sum-sub">加载失败 · 点击重试</div>
      </div>
      <div v-else class="sum-fill sk-wrap">
        <span class="sk sk-title" /><span class="sk sk-main" />
      </div>
    </div>

    <!-- ==================== 右块：剩余预算 ⇄ 月结余 ==================== -->
    <div class="sum-card" @click="onRightBody">
      <template v-if="phase === 'data'">
        <div class="sum-title">
          <template v-if="store.summaryCardRight === 'budget'">
            <span>剩余预算 ·</span>
            <span class="sum-period" @click.stop="store.cycleSummaryPeriod()">{{ periodShort }}</span>
          </template>
          <template v-else>
            <span class="sum-period" @click.stop="store.cycleSummaryPeriod()">{{ periodShort }}</span>
            <span>结余</span>
          </template>
          <van-icon name="replay" class="sum-flip" />
        </div>
        <div class="sum-main" :class="rightMainClass">
          <template v-if="rightMainValue === null">—</template>
          <MoneyText v-else :value="rightMainValue" :signed="rightSigned" />
        </div>
        <div
          class="sum-sub"
          :class="{ 'is-action': rightSubAction }"
          @click.stop="rightSubAction ? emit('goto-budget') : undefined"
        >
          <template v-if="rightSubValue === null">{{ rightSubText }}</template>
          <template v-else>{{ rightSubPrefix }}<MoneyText :value="rightSubValue" /></template>
        </div>
      </template>
      <div v-else-if="phase === 'error'" class="sum-fill">
        <div class="sum-title">
          <span>数据 ·</span>
          <span class="sum-period" @click.stop="store.cycleSummaryPeriod()">{{ periodShort }}</span>
        </div>
        <div class="sum-main">—</div>
        <div class="sum-sub">加载失败 · 点击重试</div>
      </div>
      <div v-else class="sum-fill sk-wrap">
        <span class="sk sk-title" /><span class="sk sk-main" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useFinanceStore } from '@/stores/finance'
import MoneyText from '@/components/finance/MoneyText.vue'

const emit = defineEmits<{ (e: 'goto-budget'): void }>()

const store = useFinanceStore()

/** 进视图就拉一次（数字常新；翻面/切周期的刷新由 store 动作自己触发） */
onMounted(() => {
  void store.fetchSummary()
})

/* ==================== 三态：骨架 / 错误 / 数据（01 §2.8） ==================== */
const phase = computed<'skeleton' | 'error' | 'data'>(() => {
  if (store.summaryLoading || !store.summary) return store.summaryError ? 'error' : 'skeleton'
  return 'data'
})

/* ==================== 周期文案 ==================== */
const periodShort = computed(() =>
  store.summaryPeriod === 'week' ? '周' : store.summaryPeriod === 'year' ? '年' : '月'
)
const periodPrefix = computed(() => `今${periodShort.value}`)

/* ==================== 左块 ==================== */
/** 当前面：income = 收入面 / expense = 支出面 */
const leftFace = computed<'income' | 'expense'>(() =>
  store.summaryCardLeft === 'income' ? 'income' : 'expense'
)
/** 主值（绝对值真值；+¥绿 / −¥红 由 MoneyText 的 signed 负责，遮罩态自动中性化） */
const leftMainValue = computed(() => {
  const s = store.summary
  if (!s) return 0
  return leftFace.value === 'income' ? s.income : s.expense
})
/** 副行 = 另一面（不点击也两数可见；一律无符号 ¥，主值才带符号） */
const leftSubValue = computed(() => {
  const s = store.summary
  if (!s) return 0
  return leftFace.value === 'income' ? s.expense : s.income
})

/* ==================== 右块 ==================== */
/** 主值：null = 无 total 预算（渲染 `—`，不显示 ¥0，Q3）；一律取绝对值 */
const rightMainValue = computed<number | null>(() => {
  const s = store.summary
  if (!s) return null
  if (store.summaryCardRight === 'budget') {
    return s.budget.count === 0 ? null : Math.abs(s.budget.remaining)
  }
  return Math.abs(s.net)
})
/** 主值符号：预算面只在负数带 −；结余面正 + / 负 −（U+2212，与 utils/money.ts 同约定） */
const rightSigned = computed<'' | 'income' | 'expense'>(() => {
  const s = store.summary
  if (!s) return ''
  if (store.summaryCardRight === 'budget') {
    return s.budget.count > 0 && s.budget.remaining < 0 ? 'expense' : ''
  }
  return s.net >= 0 ? 'income' : 'expense'
})
const rightMainClass = computed(() => {
  const s = store.summary
  if (!s) return ''
  if (store.summaryCardRight === 'budget') {
    return s.budget.count > 0 && s.budget.remaining < 0 ? 'is-down' : ''
  }
  return s.net >= 0 ? 'is-up' : 'is-down'
})
const rightSubAction = computed(() => {
  const s = store.summary
  return store.summaryCardRight === 'budget' && !!s && s.budget.count === 0
})
/** 副行带数字时的前缀（值走 MoneyText） */
const rightSubPrefix = computed(() =>
  store.summaryCardRight === 'budget' ? `${periodShort.value}结余 ` : '剩余预算 '
)
/** 副行数值：null = 副行不是数字（动作文案或 `—`） */
const rightSubValue = computed<number | null>(() => {
  const s = store.summary
  if (!s) return null
  if (store.summaryCardRight === 'budget') return s.budget.count === 0 ? null : s.net
  return s.budget.count === 0 ? null : s.budget.remaining
})
/** 副行纯文案（仅 rightSubValue === null 时渲染） */
const rightSubText = computed(() => {
  if (rightSubValue.value !== null) return ''
  return store.summaryCardRight === 'budget' ? '未设预算 · 去设置 ›' : '剩余预算 —'
})

/* ==================== 热区（01 §2.2） ==================== */
/** 失败态下点块体 = 重试，而不是翻面（重试成功自然回到数据态） */
function onLeftBody() {
  if (phase.value === 'error') {
    void store.fetchSummary()
    return
  }
  if (phase.value === 'data') store.flipSummaryCardLeft()
}
function onRightBody() {
  if (phase.value === 'error') {
    void store.fetchSummary()
    return
  }
  if (phase.value === 'data') store.flipSummaryCardRight()
}
</script>

<style scoped lang="scss">
/* 两卡等高 ≈76px（标题16 + 主值26 + 副行16 + 上下 padding 9×2），间距 8px（01 §2.6） */
.summary-cards {
  display: flex;
  gap: 8px;
  margin-bottom: 12px;
}

.sum-card {
  flex: 1;
  min-width: 0;
  box-sizing: border-box;
  height: 76px;
  padding: 9px 12px;
  border-radius: 12px;
  background: var(--color-bg-card);
  box-shadow: var(--shadow-xs);
  overflow: hidden;
  transition: background 0.15s;

  &:active {
    background: var(--color-bg-hover);
  }
}

.sum-fill {
  height: 100%;
}

.sum-title {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  line-height: 16px;
  color: var(--color-text-secondary);
  white-space: nowrap;
}

/* 翻面提示图标（热区①） */
.sum-flip {
  font-size: 14px;
  color: var(--color-text-tertiary);
}

/* 周期字（热区②）：primary + 下划虚线 = 可点 */
.sum-period {
  color: var(--color-primary);
  border-bottom: 1px dashed var(--color-primary);
  line-height: 14px;
  padding: 0 1px;

  &:active {
    opacity: 0.6;
  }
}

.sum-main {
  font-size: 20px;
  font-weight: 600;
  line-height: 26px;
  color: var(--color-text-primary);
  font-variant-numeric: tabular-nums;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;

  &.is-up {
    color: var(--color-success);
  }
  &.is-down {
    color: var(--color-danger);
  }
}

.sum-sub {
  font-size: 11px;
  line-height: 16px;
  color: var(--color-text-tertiary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;

  &.is-action {
    color: var(--color-primary);
  }
}

/* ==================== 骨架（01 §2.8：不做 spinner） ==================== */
.sk-wrap {
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 8px;
}

.sk {
  display: block;
  border-radius: var(--radius-sm);
  background: var(--color-bg-hover);
}

.sk-title {
  width: 44%;
  height: 12px;
}

.sk-main {
  width: 64%;
  height: 20px;
}
</style>
