// life-assisitant-ui-desktop/src/pages/home/index.tsx
/**
 * 首页 —— 私人管家「门面」（04 §4.5 信息架构重构）。
 *
 * 从「仪表盘卡片堆叠」重构为「管家问候 + 今日叙事」两栏：
 *   ① 问候条 + 今日状态（心情/精力）+ 快捷入口
 *   ② 4 张 KPI 卡
 *   ③ 管家建议（SmartBanner，可操作 / 可关闭 / 多条轮播）
 *   ④ 今日时间线（主区 2/3，吸收「今日任务卡」）  │ ⑤ 今日习惯
 *                                                 │ ⑥ 本月财务
 *
 * 数据：homeApi（聚合）、timelineApi（时间线）、moodStore（心情）、habitStore（习惯/streak）。
 * 首页与时间线直接走 API 并持有本地 loading/error 状态，以便区分「加载失败」与「暂无数据」。
 */
import { useCallback, useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import { Card, Skeleton, Button, Tooltip } from '@douyinfe/semi-ui'
import { Icon, TINT_VARS } from '@/components/icon'
import type { IconName, TintName } from '@/components/icon'
import { homeApi } from '@/api/home'
import { timelineApi } from '@/api/timeline'
import { useMoodStore } from '@/stores/mood'
import { useHabitStore } from '@/stores/habit'
import { resolveHabitIconView } from '@/utils/category-dict'
import { moodOptions, energyOptions, MOOD_VALUES_ASC } from '@/utils/mood-dict'
import ErrorState from '@/components/ErrorState'
import { MoneyText } from '@/components/finance/MoneyText'
import { EmptyHint } from '@/components/EmptyState'
import AnniversaryCard from '@/components/AnniversaryCard'
import { SmartBanner, computeRecs } from '@/components/SmartBanner'
import Timeline from './Timeline'
import MoodSection from '@/pages/record/components/MoodSection'
import type { HomeResp, TimelineEvent, MoodValue, EnergyValue } from '@/api/types'

/** 本地时区当天日期 YYYY-MM-DD（避免 toISOString 的 UTC 偏移跨天） */
function todayStr(d: Date = new Date()): string {
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

/** SVG 进度环 helper */
function progressArc(pct: number, size = 80, stroke = 8) {
  const r = (size - stroke) / 2
  const c = 2 * Math.PI * r
  const offset = c * (1 - Math.min(pct, 100) / 100)
  return { r, c, offset, size, stroke }
}

/** KPI 涨跌指示（Lucide 图标） */
function KpiChange({ value }: { value: number }) {
  if (value === 0) return null
  const isUp = value > 0
  const color = isUp ? 'var(--color-success)' : 'var(--color-danger)'
  return (
    <span style={{ fontSize: 11, color, fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: 2 }}>
      <Icon name={isUp ? 'TrendingUp' : 'TrendingDown'} size={14} />
      {Math.abs(value).toFixed(1)}%
    </span>
  )
}

// 心情 / 精力档位元数据统一走 utils/mood-dict.ts（首页、记录页、左下角面板共用一份），
// 这里只声明本页的展示顺序：从左到右「很差 → 很好」。
const MOOD_OPTIONS = moodOptions(MOOD_VALUES_ASC)
const ENERGY_OPTIONS = energyOptions([1, 2, 3])

/** 快捷入口（04 §4.5：取消 2×2，收进问候条右侧） */
const QUICK_ENTRIES: { icon: IconName; label: string; route: string }[] = [
  { icon: 'PlusCircle', label: '记一笔', route: '/record' },
  { icon: 'ListChecks', label: '新建任务', route: '/todo' },
  { icon: 'BarChart3', label: '统计', route: '/stat' },
  { icon: 'User', label: '我的', route: '/me' },
]

/** KPI 卡配置（H2：6 种 tint） */
const KPI_ITEMS: { key: string; icon: IconName; tint: TintName; label: string; route: string }[] = [
  { key: 'todo', icon: 'ListChecks', tint: 'primary', label: '今日任务', route: '/todo' },
  { key: 'habit', icon: 'CalendarCheck', tint: 'warning', label: '今日习惯', route: '/record' },
  { key: 'expense', icon: 'TrendingDown', tint: 'danger', label: '本月支出', route: '/stat' },
  { key: 'income', icon: 'TrendingUp', tint: 'success', label: '本月收入', route: '/stat' },
]

export default function HomePage() {
  const navigate = useNavigate()
  const moodStore = useMoodStore()
  const habitStore = useHabitStore()

  // —— 首页聚合数据（本地状态，以便区分 error / empty）——
  const [home, setHome] = useState<HomeResp | null>(null)
  const [homeLoading, setHomeLoading] = useState(true)
  const [homeError, setHomeError] = useState(false)

  // —— 时间线数据 ——
  const [timelineItems, setTimelineItems] = useState<TimelineEvent[]>([])
  const [timelineLoading, setTimelineLoading] = useState(true)
  const [timelineError, setTimelineError] = useState(false)

  const refresh = useCallback(async () => {
    setHomeLoading(true)
    setHomeError(false)
    setTimelineLoading(true)
    setTimelineError(false)

    const [homeRes, timelineRes] = await Promise.allSettled([
      homeApi.fetch(),
      timelineApi.getTimeline({ date: todayStr() }),
    ])

    if (homeRes.status === 'fulfilled') {
      setHome(homeRes.value)
    } else {
      setHome(null)
      setHomeError(true)
    }
    setHomeLoading(false)

    if (timelineRes.status === 'fulfilled') {
      setTimelineItems(timelineRes.value.items ?? [])
    } else {
      setTimelineItems([])
      setTimelineError(true)
    }
    setTimelineLoading(false)
  }, [])

  useEffect(() => {
    refresh()
    // 拉时间线而不是只拉 today：顺带拿到服务端 now_hour，点心情才能落到正确的小时
    moodStore.fetchTimeline()
    habitStore.fetchList()
  }, [refresh])

  const kpi = home?.kpi
  const todayHabits = home?.today_habits ?? []
  const monthFinance = home?.month_finance
  const dateText = home?.today_date && home?.weekday ? `${home.today_date} · ${home.weekday}` : ''

  const todoProgress = kpi ? Math.round(kpi.todo_rate * 100) : 0
  const habitProgress = kpi ? (kpi.habit_total > 0 ? Math.round((kpi.habit_done / kpi.habit_total) * 100) : 0) : 0

  const habitArc = useMemo(() => progressArc(habitProgress, 100, 10), [habitProgress])

  // 最长连续天数（首页习惯卡环形图下方一行，04 §2.4）
  const longestStreak = useMemo(
    () => Math.max(0, ...habitStore.items.map((h) => h.longest_streak ?? 0)),
    [habitStore.items],
  )

  // 管家建议（含断卡预警 / 里程碑临近）
  const recs = useMemo(
    () => computeRecs(home, habitStore.items, new Date()),
    [home, habitStore.items],
  )

  // —— 心情 / 精力选择 ——
  // 新契约是按小时记录：只发被点的那一个字段，绝不动另一个；
  // 再点当前已选中的同一个值 = 显式发 0（这一小时不再单独记，显示回落到延续值）。
  function onPickMood(mood: MoodValue) {
    const cur = moodStore.current?.mood ?? 0
    void moodStore.setMood(cur === mood ? 0 : mood)
  }
  function onPickEnergy(energy: EnergyValue) {
    const cur = moodStore.current?.energy ?? 0
    void moodStore.setEnergy(cur === energy ? 0 : energy)
  }

  // —— 习惯打卡（完成后刷新首页 + 时间线，使卡片与叙事同步）——
  /** 只需要 id：首页简表 HomeHabitItem 也能直接打卡 */
  async function onCheckIn(h: { id: string }) {
    await habitStore.checkIn(h.id)
    refresh()
  }

  /** KPI 卡渲染（4 张统一结构） */
  function renderKpi(icon: IconName, tint: TintName, label: string, route: string, value: ReactNode, foot: ReactNode) {
    const tv = TINT_VARS[tint]
    return (
      <div className="kpi-card" onClick={() => navigate(route)}>
        <div className="kpi-icon" style={{ background: tv.bg, color: tv.fg }}>
          <Icon name={icon} size={20} />
        </div>
        <div className="kpi-body">
          <div className="kpi-label">{label}</div>
          <div className="kpi-value">{value}</div>
          <div className="kpi-foot">{foot}</div>
        </div>
      </div>
    )
  }

  // 整体加载骨架（首页聚合数据首次加载）
  if (homeLoading && !home) {
    return (
      <div className="home-page">
        <Skeleton.Title style={{ width: 300, marginBottom: 24 }} />
        <Skeleton.Paragraph rows={8} />
      </div>
    )
  }

  // 首页聚合数据加载失败（网络异常等）—— 与「暂无数据」区分
  if (homeError && !home) {
    return (
      <div className="home-page">
        <div className="card">
          <ErrorState message="首页数据加载失败，请检查网络后重试" onRetry={refresh} />
        </div>
      </div>
    )
  }

  return (
    <div className="home-page">
      {/* ① 问候条 + 今日状态 + 快捷入口 */}
      <div className="welcome">
        <div className="welcome-left">
          <div className="welcome-sun"><Icon name="Sun" size={24} /></div>
          <div>
            <div className="greet-line1">{home?.greeting ?? ''}</div>
            <div className="greet-line2">{dateText} · 今天也要加油鸭</div>
          </div>
        </div>

        <div className="welcome-right">
          {/* 心情 / 精力（常驻，04 §3.2） */}
          <div className="mood-picker" role="group" aria-label="今日心情与精力">
            <div className="mood-group">
              {MOOD_OPTIONS.map((o) => {
                const active = moodStore.current?.mood === o.value
                const tv = TINT_VARS[o.tint]
                return (
                  <Tooltip key={o.value} content={o.label}>
                    <button
                      className={`mood-btn${active ? ' active' : ''}`}
                      onClick={() => onPickMood(o.value)}
                      style={active ? { background: '#fff', color: tv.fg } : undefined}
                    >
                      <Icon name={o.icon} size={16} />
                    </button>
                  </Tooltip>
                )
              })}
            </div>
            <span className="mood-sep" />
            <div className="mood-group">
              {ENERGY_OPTIONS.map((o) => {
                const active = moodStore.current?.energy === o.value
                const tv = TINT_VARS[o.tint]
                return (
                  <Tooltip key={o.value} content={o.label}>
                    <button
                      className={`mood-btn${active ? ' active' : ''}`}
                      onClick={() => onPickEnergy(o.value)}
                      style={active ? { background: '#fff', color: tv.fg } : undefined}
                    >
                      <Icon name={o.icon} size={16} />
                    </button>
                  </Tooltip>
                )
              })}
            </div>
          </div>

          {/* 快捷入口 */}
          <div className="welcome-actions">
            {QUICK_ENTRIES.map((q) => (
              <button key={q.route} className="welcome-action" onClick={() => navigate(q.route)}>
                <Icon name={q.icon} size={16} />
                <span>{q.label}</span>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* ② 4 张 KPI */}
      <div className="kpi-row">
        {renderKpi(
          KPI_ITEMS[0].icon, KPI_ITEMS[0].tint, KPI_ITEMS[0].label, KPI_ITEMS[0].route,
          <>{kpi?.todo_done ?? 0}<span className="kpi-value-sub">/{kpi?.todo_total ?? 0}</span></>,
          <>
            <div className="kpi-bar"><div className="kpi-bar-fill" style={{ width: todoProgress + '%', background: 'var(--color-primary-500)' }} /></div>
            <span className="kpi-foot-text">{todoProgress}%</span>
          </>,
        )}
        {renderKpi(
          KPI_ITEMS[1].icon, KPI_ITEMS[1].tint, KPI_ITEMS[1].label, KPI_ITEMS[1].route,
          <>{kpi?.habit_done ?? 0}<span className="kpi-value-sub">/{kpi?.habit_total ?? 0}</span></>,
          <>
            <div className="kpi-bar"><div className="kpi-bar-fill" style={{ width: habitProgress + '%', background: 'var(--color-warning)' }} /></div>
            <span className="kpi-foot-text">{habitProgress}%</span>
          </>,
        )}
        {renderKpi(
          KPI_ITEMS[2].icon, KPI_ITEMS[2].tint, KPI_ITEMS[2].label, KPI_ITEMS[2].route,
          <span style={{ color: 'var(--color-danger-dark)' }}><MoneyText value={kpi?.month_expense ?? 0} /></span>,
          <>
            <KpiChange value={kpi?.month_expense_change ?? 0} />
            <span className="kpi-foot-text muted">同比</span>
          </>,
        )}
        {renderKpi(
          KPI_ITEMS[3].icon, KPI_ITEMS[3].tint, KPI_ITEMS[3].label, KPI_ITEMS[3].route,
          <span style={{ color: 'var(--color-success-dark)' }}><MoneyText value={kpi?.month_income ?? 0} /></span>,
          <>
            <KpiChange value={kpi?.month_income_change ?? 0} />
            <span className="kpi-foot-text muted">同比</span>
          </>,
        )}
      </div>

      {/* ③ 管家建议 */}
      <SmartBanner recs={recs} />

      {/* ④⑤⑥ 两栏：时间线（主区） | 今日习惯 + 本月财务 */}
      <div className="home-columns">
        <Card bordered={false} className="card timeline-card">
          <div className="card-head">
            <span className="card-title"><Icon name="History" size={20} style={{ marginRight: 6 }} />今日时间线</span>
            <span className="card-sub">{home?.today_date ?? todayStr()}</span>
          </div>

          {timelineLoading ? (
            <div className="timeline-skeleton">
              {[1, 2, 3, 4, 5].map((i) => (
                <div key={i} className="timeline-skeleton-row">
                  <Skeleton.Title style={{ width: 32, margin: 0 }} />
                  <Skeleton.Paragraph rows={1} style={{ flex: 1, margin: 0 }} />
                </div>
              ))}
            </div>
          ) : timelineError ? (
            <ErrorState compact message="时间线加载失败，请重试" onRetry={refresh} />
          ) : timelineItems.length > 0 ? (
            <Timeline items={timelineItems} />
          ) : (
            <EmptyHint
              icon="Inbox"
              title="今天还没有记录"
              desc="完成的任务、习惯打卡和记账会出现在这里，连成你的一天"
            />
          )}
        </Card>

        <div className="home-side-col">
          {/* ⑤ 今日习惯 */}
          <Card bordered={false} className="card habit-check-card">
            <div className="card-head">
              <span className="card-title"><Icon name="CalendarCheck" size={20} style={{ marginRight: 6 }} />今日习惯</span>
              <a className="view-all" onClick={() => navigate('/record')}>全部</a>
            </div>

            {todayHabits.length > 0 ? (
              <div className="habit-check-row">
                <div className="habit-ring-wrap">
                  <svg width={habitArc.size} height={habitArc.size}>
                    <circle cx={habitArc.size / 2} cy={habitArc.size / 2} r={habitArc.r} stroke="var(--color-bg-hover)" strokeWidth={habitArc.stroke} fill="none" />
                    <circle
                      cx={habitArc.size / 2} cy={habitArc.size / 2} r={habitArc.r} stroke="var(--color-warning)" strokeWidth={habitArc.stroke} fill="none"
                      strokeDasharray={habitArc.c} strokeDashoffset={habitArc.offset} strokeLinecap="round"
                      transform={`rotate(-90 ${habitArc.size / 2} ${habitArc.size / 2})`}
                    />
                    <text x={habitArc.size / 2} y={habitArc.size / 2} textAnchor="middle" dominantBaseline="central"
                      className="habit-ring-value">
                      {kpi?.habit_done ?? 0}
                    </text>
                    <text x={habitArc.size / 2} y={habitArc.size / 2 + 18} textAnchor="middle" dominantBaseline="central"
                      style={{ fontSize: 11, fill: 'var(--color-text-tertiary)' }}>
                      / {kpi?.habit_total ?? 0}
                    </text>
                  </svg>
                  {longestStreak > 0 && (
                    <div className="habit-ring-sub">最长连续 {longestStreak} 天</div>
                  )}
                </div>

                <div className="habit-check-list">
                  {todayHabits.map((h) => {
                    // HomeHabitItem 无 category/icon 之外的分类信息 ⇒ 回 habit store 按 id 兜底，
                    // 再走 04 §4.2 优先级链：habits.icon > 分类.icon > 分类.emoji > lucide:Pin
                    const sh = habitStore.items.find((x) => x.id === h.id)
                    const iv = resolveHabitIconView({ icon: sh?.icon || h.icon, category: sh?.category })
                    const done = h.completed
                    const pct = h.target_count > 0 ? Math.min(100, Math.round(((h.today_count ?? 0) / h.target_count) * 100)) : 0
                    const tv = TINT_VARS[iv.tint]
                    return (
                      <div key={h.id} className={`habit-check-item${done ? ' done' : ''}`}>
                        <div className="hci-icon" style={{ background: tv.bg, color: tv.fg }}>
                          <Icon name={iv.icon} size={16} />
                        </div>
                        <div className="hci-body">
                          <div className="hci-title">{h.title}</div>
                          <div className="hci-sub">
                            <div className="hci-bar">
                              <div className="hci-bar-fill" style={{ width: pct + '%', background: done ? 'var(--color-success)' : h.color || 'var(--color-primary-500)' }} />
                            </div>
                            <span className="hci-pct">{h.today_count ?? 0}/{h.target_count} {sh?.unit ?? ''}</span>
                          </div>
                        </div>
                        <Tooltip content={done ? '已打卡' : '打卡'}>
                          <Button
                            theme={done ? 'light' : 'solid'}
                            type={done ? 'tertiary' : 'primary'}
                            size="small"
                            icon={<Icon name="CheckSquare" size={16} />}
                            disabled={done}
                            onClick={() => onCheckIn(h)}
                          />
                        </Tooltip>
                      </div>
                    )
                  })}
                </div>
              </div>
            ) : (
              <EmptyHint icon="FolderOpen" title="还没有习惯" desc="去记录页创建你的第一个习惯吧" />
            )}
          </Card>

          {/* ⑥ 本月财务 */}
          <Card bordered={false} className="card">
            <div className="card-head">
              <span className="card-title"><Icon name="CreditCard" size={20} style={{ marginRight: 6 }} />本月财务</span>
              <a className="view-all" onClick={() => navigate('/stat')}>详情</a>
            </div>

            {monthFinance ? (
              <>
                <div className="finance-summary">
                  <div className="finance-summary-item is-expense">
                    <div className="finance-summary-label">支出</div>
                    <div className="finance-summary-value"><MoneyText value={monthFinance.expense} /></div>
                    <KpiChange value={monthFinance.expense_change} />
                  </div>
                  <div className="finance-summary-item is-income">
                    <div className="finance-summary-label">收入</div>
                    <div className="finance-summary-value"><MoneyText value={monthFinance.income} /></div>
                    <KpiChange value={monthFinance.income_change} />
                  </div>
                </div>

                {monthFinance.category_pie.length > 0 && (
                  <div className="finance-cats">
                    <div className="finance-cats-title">分类占比</div>
                    {monthFinance.category_pie.slice(0, 4).map((cat) => {
                      const pct = monthFinance.expense > 0 ? Math.round((cat.value / monthFinance.expense) * 100) : 0
                      return (
                        <div key={cat.name} className="finance-cat-row">
                          <span className="finance-cat-dot" style={{ background: cat.color }} />
                          <span className="finance-cat-name">{cat.name}</span>
                          <span className="finance-cat-value"><MoneyText value={cat.value} /></span>
                          <span className="finance-cat-pct">{pct}%</span>
                        </div>
                      )
                    })}
                  </div>
                )}
              </>
            ) : (
              <EmptyHint icon="FolderOpen" title="暂无财务数据" />
            )}
          </Card>

          {/* ⑥.5 重要日子（纪念日 / 倒数日）
               位置按 spec 06 §2：本月财务之后（与移动端同序）。
               ⚠️ 一条都没有时组件内部整卡不渲染，这里不额外判空。 */}
          <AnniversaryCard />

          {/* ⑦ 今日心情（完整卡，全量、不折叠）
               与顶栏「此刻」1-tap 快捷并存：欢迎条负责一眼点选，
               这里给出按小时记录 + 全天时间线的完整视图（双轴之一：心情/精力轴）。
               collapse 不传 → 默认 false → 全量渲染。 */}
          <MoodSection />
        </div>
      </div>
    </div>
  )
}

// life-assisitant-ui-mobile/src/pages/home/index.vue
<script setup lang="ts">
/**
 * 首页（移动端 · Phase 2.1 + 2.2）
 *
 * SYNC-FROM-DESKTOP: life-assisitant-ui-desktop/src/pages/home/index.tsx
 * SYNC-FROM-BACKEND: life-assisitant-api/internal/model/dto/home.go
 * 最后同步：2026-09-18
 *
 * Phase 2 改动：
 *   2.1 数据源由「拼 4 个接口」改为 `/home` 聚合接口一次请求
 *       （+ `/timeline` 取今日事件流，两个请求 allSettled 并发、各自独立错误态）
 *   2.2 新增：心情/精力区、第 4 个 KPI（本月收入）、管家建议横幅、今日时间线；
 *       习惯区补「完成环 + 最长连续」，财务区补「分类占比」
 *
 * 与桌面端的差异（刻意）：
 *   - 桌面端 `todoProgress = kpi.todo_rate * 100` —— 但后端 `todo_rate` 注释明确是
 *     **0-100**（`model/dto/home.go`），桌面端这一处多乘了 100（进度条恒 100%）。
 *     移动端按后端口径直接用，不再复刻该缺陷。
 *   - 桌面端习惯列表读 `h.category` / `h.unit`，但 `HomeHabitItem` 结构里没有这两个
 *     字段（见 dto/home.go）→ 桌面端所有首页习惯图标都降级成灰色。
 *     移动端改用响应里真实存在的 `icon` / `color` 渲染，单位从 habit store 兜底查。
 */
import { computed, onMounted, ref, watchEffect } from 'vue'
import { useRouter } from 'vue-router'
import { storeToRefs } from 'pinia'
import { useUiStore } from '@/stores/ui'
import { useTaskStore } from '@/stores/task'
import { useHabitStore } from '@/stores/habit'
import { useFinanceStore } from '@/stores/finance'
import { useMoodStore } from '@/stores/mood'
import { homeApi } from '@/api/home'
import { timelineApi } from '@/api/timeline'
import TransactionEditSheet from '@/components/TransactionEditSheet.vue'
import SmartBanner from '@/components/SmartBanner.vue'
import AnniversaryCard from '@/components/AnniversaryCard.vue'
import Timeline from '@/components/Timeline.vue'
import MoodSection from '@/components/MoodSection.vue'
import type {
  CreateTransactionReq,
  HomeResp,
  TimelineEvent,
  TransferReq,
  TransactionType,
  UpdateTransactionReq,
} from '@/api/types'
import { getTint, type TintName } from '@/utils/tint'
import { formatMoney, formatMonthDayWeekday, greetingByHour, todayDate } from '@/utils/date'
import Icon from '@/components/icon/Icon.vue'
import type { IconName } from '@/components/icon/names'
import { getIconMapping } from '@/utils/icon-map'
import { computeRecs } from '@/utils/smart-recs'

const router = useRouter()
const taskStore = useTaskStore()
const habitStore = useHabitStore()
const financeStore = useFinanceStore()
const moodStore = useMoodStore()

const { accounts } = storeToRefs(financeStore)

// 顶部栏（头像 + 问候语 + 日期）已提到 HomeLayout 常驻渲染，
// 本页通过 uiStore 把 /home 接口回来的文案推上去（见下方 watchEffect）。
const ui = useUiStore()

// ==================== 聚合数据（本地 loading / error，区分「加载失败」与「暂无数据」） ====================
const home = ref<HomeResp | null>(null)
const homeLoading = ref(true)
const homeError = ref(false)

const timelineItems = ref<TimelineEvent[]>([])
const timelineLoading = ref(true)
const timelineError = ref(false)

async function refresh(): Promise<void> {
  homeLoading.value = true
  homeError.value = false
  timelineLoading.value = true
  timelineError.value = false

  const [homeRes, timelineRes] = await Promise.allSettled([
    homeApi.fetch(),
    timelineApi.fetch({ date: todayDate() }),
  ])

  if (homeRes.status === 'fulfilled') {
    home.value = homeRes.value
  } else {
    home.value = null
    homeError.value = true
  }
  homeLoading.value = false

  if (timelineRes.status === 'fulfilled') {
    timelineItems.value = timelineRes.value.items ?? []
  } else {
    timelineItems.value = []
    timelineError.value = true
  }
  timelineLoading.value = false
}

// ==================== 欢迎语 ====================
// 顶部栏（头像 + 问候语 + 日期）现在由 HomeLayout 常驻渲染（见 components/PageHeader.vue
// + composables/usePageChrome.ts）。本页只负责把「接口回来的文案」推上去：
// 后端 greeting 带 ☀️🌤️ 等 emoji、日期用 today_date · weekday，比本地兜底更准。
// 接口没回来前 greeting / dateText 本身就有本地兜底值，所以推上去也不会空。
const greeting = computed(() => home.value?.greeting || greetingByHour())
const dateText = computed(() => {
  const h = home.value
  if (h?.today_date && h?.weekday) return `${h.today_date} · ${h.weekday}`
  return formatMonthDayWeekday(todayDate())
})

watchEffect(() => {
  ui.setHomeHeader(greeting.value, dateText.value)
})

// ==================== KPI ====================
const kpi = computed(() => home.value?.kpi ?? null)

/** 任务完成率（后端 0-100，直接用，不再 ×100） */
const todoProgress = computed(() => clampPct(kpi.value?.todo_rate ?? 0))
/** 习惯完成率（后端只给 done/total，自行换算） */
const habitProgress = computed(() => {
  const k = kpi.value
  if (!k || k.habit_total <= 0) return 0
  return clampPct((k.habit_done / k.habit_total) * 100)
})

interface KpiCell {
  key: string
  label: string
  icon: IconName
  tint: TintName
  value: string
  sub?: string
  progress?: number
  route: string
}

const kpiCells = computed<KpiCell[]>(() => {
  const k = kpi.value
  return [
    {
      key: 'todo',
      label: '今日任务',
      icon: 'ListChecks',
      tint: 'primary',
      value: `${k?.todo_done ?? 0}`,
      sub: `/${k?.todo_total ?? 0}`,
      progress: todoProgress.value,
      route: '/task',
    },
    {
      key: 'habit',
      label: '今日习惯',
      icon: 'Flame',
      tint: 'warning',
      value: `${k?.habit_done ?? 0}`,
      sub: `/${k?.habit_total ?? 0}`,
      progress: habitProgress.value,
      route: '/record',
    },
    {
      key: 'expense',
      label: '本月支出',
      icon: 'Banknote',
      tint: 'danger',
      value: `¥${formatMoney(k?.month_expense ?? 0, true)}`,
      route: '/stat',
    },
    {
      key: 'income',
      label: '本月收入',
      icon: 'Banknote',
      tint: 'success',
      value: `¥${formatMoney(k?.month_income ?? 0, true)}`,
      route: '/stat',
    },
  ]
})

/** KPI 涨跌（同比 %）；0 不显示 */
function changeLabel(v?: number): string {
  if (!v) return ''
  return `${v > 0 ? '+' : ''}${v.toFixed(1)}%`
}
function changeColor(v?: number): string {
  if (!v) return 'var(--color-text-tertiary)'
  // 支出涨 = 差（红），收入涨 = 好（绿）—— 此处沿用桌面端的 ± 方向色
  return v > 0 ? 'var(--color-danger-dark)' : 'var(--color-success-dark)'
}

// ==================== 管家建议 ====================
const recs = computed(() => computeRecs(home.value, habitStore.habits, new Date()))

// ==================== 今日习惯 ====================
const todayHabits = computed(() => home.value?.today_habits ?? [])

/** 习惯环 SVG 参数（size 88 / stroke 9） */
const habitArc = computed(() => {
  const size = 88
  const stroke = 9
  const r = (size - stroke) / 2
  const c = 2 * Math.PI * r
  return { size, stroke, r, c, offset: c * (1 - habitProgress.value / 100) }
})

/** 最长连续天数（首页习惯卡环形图下方一行） */
const longestStreak = computed(() =>
  habitStore.habits.reduce((max, h) => Math.max(max, h.longest_streak ?? 0), 0)
)

/** 习惯单位：HomeHabitItem 不含 unit，从 habit store 兜底查 */
function habitUnit(id: string): string {
  return habitStore.findById(id)?.unit ?? ''
}

function habitPct(item: { today_count: number; target_count: number }): number {
  if (item.target_count <= 0) return 0
  return Math.min(100, Math.round((item.today_count / item.target_count) * 100))
}

/**
 * 打卡（B2 修复点：`LogHabitReq` 字段名是 `date`，此前首页传 `log_date` 静默失效）
 * 打卡后同时刷新聚合数据 + 时间线 + 习惯列表，使三处同步。
 */
async function onCheckIn(id: string): Promise<void> {
  const ok = await habitStore.logHabit(id, { date: todayDate(), count: 1 })
  if (ok) await refresh()
}

// ==================== 本月财务 ====================
const monthFinance = computed(() => home.value?.month_finance ?? null)

/** 分类占比（最多 4 条，百分比相对本月支出） */
const financeCats = computed(() => {
  const mf = monthFinance.value
  if (!mf || mf.category_pie.length === 0) return []
  return mf.category_pie.slice(0, 4).map((c) => ({
    ...c,
    pct: mf.expense > 0 ? Math.round((c.value / mf.expense) * 100) : 0,
  }))
})

// ==================== 快捷入口 ====================
interface QuickItem {
  key: string
  label: string
  icon: IconName
  bg: string
  color: string
  onClick: () => void
}

const quickItems = computed<QuickItem[]>(() => {
  const task = getTint('primary')
  const habit = getTint('success')
  const tx = getTint('warning')
  const stat = getTint('accent')
  return [
    {
      key: 'tx',
      label: '记一笔',
      icon: 'Banknote',
      bg: tx.bg,
      color: tx.fg,
      onClick: () => { txSheetShow.value = true },
    },
    {
      key: 'task',
      label: '新建任务',
      icon: 'ListChecks',
      bg: task.bg,
      color: task.fg,
      onClick: () => router.push('/task'),
    },
    {
      key: 'habit',
      label: '去打卡',
      icon: 'Sprout',
      bg: habit.bg,
      color: habit.fg,
      onClick: () => router.push('/record'),
    },
    {
      key: 'stat',
      label: '查看统计',
      icon: 'BarChart3',
      bg: stat.bg,
      color: stat.fg,
      onClick: () => router.push('/stat'),
    },
  ]
})

// ==================== 记一笔弹层 ====================
const txSheetShow = ref(false)
/**
 * 首页只做「新建」（记一笔 / 转账），编辑走记录页。
 * 第三个参数 `mode` 是 Phase 3.4 给 TransactionEditSheet 加编辑模式时引入的，
 * 首页恒为 'create'。
 */
async function onQuickTxSave(
  payload: CreateTransactionReq | TransferReq | UpdateTransactionReq,
  type: TransactionType,
  _mode: 'create' | 'update' = 'create'
): Promise<boolean> {
  if (type === 'transfer') {
    const r = await financeStore.transfer(payload as TransferReq)
    if (r !== null) await refresh()
    return r !== null
  }
  const r = await financeStore.createTransaction(payload as CreateTransactionReq)
  if (r !== null) await refresh()
  return r !== null
}

// ==================== 生命周期 ====================
onMounted(async () => {
  await Promise.all([
    refresh(),
    moodStore.fetchByDate(todayDate()),
    habitStore.fetchHabits(),
    financeStore.fetchAccounts(),
    // 首页也预载今日待办，供「今日时间线」之外的即时跳转兜底
    taskStore.fetchTasks('today'),
  ])
})

/** 把任意数值夹到 0-100 */
function clampPct(n: number): number {
  if (!Number.isFinite(n)) return 0
  return Math.max(0, Math.min(100, Math.round(n)))
}
</script>

<template>
  <div class="home-page">
    <!-- 顶部栏（头像 + 问候语 + 日期）已提到 HomeLayout 常驻渲染
         （components/PageHeader.vue 的 hero 变体 + composables/usePageChrome.ts），
         本页只把文案通过 uiStore 推上去，见 script 里的 watchEffect。 -->

    <main class="home-body">
      <!-- ① 心情 / 精力（常驻，点选即 upsert；完整卡，不折叠，全量时间线） -->
      <MoodSection />

      <!-- ② 4 张 KPI（2×2） -->
      <section class="kpi-grid">
        <button
          v-for="k in kpiCells"
          :key="k.key"
          type="button"
          class="kpi-card"
          @click="router.push(k.route)"
        >
          <div class="kpi-head">
            <span
              class="kpi-emoji"
              :style="{ background: getTint(k.tint).bg }"
              aria-hidden="true"
            ><Icon :name="k.icon" :size="16" :style="{ color: getTint(k.tint).fg }" /></span>
            <span class="kpi-label">{{ k.label }}</span>
          </div>
          <div class="kpi-value" :style="{ color: getTint(k.tint).fg }">
            {{ k.value }}<span v-if="k.sub" class="kpi-value-sub">{{ k.sub }}</span>
          </div>
          <div v-if="k.progress !== undefined" class="kpi-foot">
            <div class="kpi-bar">
              <div
                class="kpi-bar-fill"
                :style="{ width: k.progress + '%', background: getTint(k.tint).fg }"
              />
            </div>
            <span class="kpi-foot-text">{{ k.progress }}%</span>
          </div>
          <div v-else class="kpi-foot">
            <span
              v-if="k.key === 'expense' && kpi?.month_expense_change"
              class="kpi-change"
              :style="{ color: changeColor(kpi.month_expense_change) }"
            >{{ changeLabel(kpi.month_expense_change) }}</span>
            <span
              v-else-if="k.key === 'income' && kpi?.month_income_change"
              class="kpi-change"
              :style="{ color: changeColor(kpi.month_income_change) }"
            >{{ changeLabel(kpi.month_income_change) }}</span>
            <span class="kpi-foot-text muted">同比</span>
          </div>
        </button>
      </section>

      <!-- ③ 管家建议横幅 -->
      <SmartBanner :recs="recs" />

      <!-- ④ 今日时间线 -->
      <section class="card">
        <div class="card-head">
          <h3 class="card-title">今日时间线</h3>
          <span class="card-sub">{{ home?.today_date ?? todayDate() }}</span>
        </div>

        <div v-if="timelineLoading" class="panel-skel">
          <div v-for="i in 3" :key="i" class="skel-row" />
        </div>
        <div v-else-if="timelineError" class="panel-error">
          <span>时间线加载失败</span>
          <button type="button" class="retry-btn" @click="refresh">重试</button>
        </div>
        <div v-else-if="timelineItems.length === 0" class="panel-empty">
          <Icon name="Clock" :size="32" class="empty-emoji" aria-hidden="true" />
          <span>今天还没有记录</span>
          <span class="empty-desc">完成的任务、习惯打卡和记账会出现在这里</span>
        </div>
        <Timeline v-else :items="timelineItems" />
      </section>

      <!-- ⑤ 今日习惯 -->
      <section class="card">
        <div class="card-head">
          <h3 class="card-title">今日习惯</h3>
          <button type="button" class="card-more" @click="router.push('/record')">全部 ›</button>
        </div>

        <div v-if="homeLoading && !home" class="panel-skel">
          <div v-for="i in 2" :key="i" class="skel-row" />
        </div>
        <div v-else-if="todayHabits.length === 0" class="panel-empty">
          <Icon name="Sprout" :size="32" class="empty-emoji" aria-hidden="true" />
          <span>还没有习惯</span>
          <span class="empty-desc">去记录页创建你的第一个习惯吧</span>
        </div>
        <div v-else class="habit-wrap">
          <!-- 完成环 + 最长连续 -->
          <div class="habit-ring-wrap">
            <svg :width="habitArc.size" :height="habitArc.size" class="habit-ring">
              <circle
                :cx="habitArc.size / 2" :cy="habitArc.size / 2" :r="habitArc.r"
                stroke="var(--color-bg-hover)" :stroke-width="habitArc.stroke" fill="none"
              />
              <circle
                :cx="habitArc.size / 2" :cy="habitArc.size / 2" :r="habitArc.r"
                stroke="var(--color-warning)" :stroke-width="habitArc.stroke" fill="none"
                :stroke-dasharray="habitArc.c" :stroke-dashoffset="habitArc.offset"
                stroke-linecap="round"
                :transform="`rotate(-90 ${habitArc.size / 2} ${habitArc.size / 2})`"
              />
              <text
                :x="habitArc.size / 2" :y="habitArc.size / 2 - 4"
                text-anchor="middle" dominant-baseline="central" class="ring-value"
              >{{ kpi?.habit_done ?? 0 }}</text>
              <text
                :x="habitArc.size / 2" :y="habitArc.size / 2 + 14"
                text-anchor="middle" dominant-baseline="central" class="ring-sub"
              >/ {{ kpi?.habit_total ?? 0 }}</text>
            </svg>
            <div v-if="longestStreak > 0" class="ring-caption">最长连续 {{ longestStreak }} 天</div>
          </div>

          <ul class="habit-list">
            <li v-for="h in todayHabits" :key="h.id" class="habit-line" :class="{ 'is-done': h.completed }">
              <span class="habit-emoji" :style="{ background: h.color + '22' }" aria-hidden="true">
                <Icon :name="getIconMapping(h.icon).icon" :size="16" :style="{ color: getIconMapping(h.icon).vars.fg }" />
              </span>
              <div class="habit-body">
                <div class="habit-name">{{ h.title }}</div>
                <div class="habit-progress-row">
                  <div class="habit-bar">
                    <div
                      class="habit-bar-fill"
                      :style="{
                        width: habitPct(h) + '%',
                        background: h.completed ? 'var(--color-success)' : h.color,
                      }"
                    />
                  </div>
                  <span class="habit-count">
                    {{ h.today_count }}/{{ h.target_count }}{{ habitUnit(h.id) }}
                  </span>
                </div>
              </div>
              <button
                type="button"
                class="habit-check"
                :disabled="h.completed"
                :aria-label="h.completed ? '已打卡' : '打卡'"
                @click="onCheckIn(h.id)"
              >{{ h.completed ? '✓' : '+' }}</button>
            </li>
          </ul>
        </div>
      </section>

      <!-- ⑥ 本月财务 -->
      <section class="card">
        <div class="card-head">
          <h3 class="card-title">本月财务</h3>
          <button type="button" class="card-more" @click="router.push('/stat')">详情 ›</button>
        </div>

        <template v-if="monthFinance">
          <div class="finance-summary">
            <div class="finance-cell">
              <div class="finance-label">支出</div>
              <div class="finance-value is-expense">¥{{ formatMoney(monthFinance.expense, true) }}</div>
              <div class="kpi-change" :style="{ color: changeColor(monthFinance.expense_change) }">
                {{ changeLabel(monthFinance.expense_change) }}
              </div>
            </div>
            <div class="finance-cell">
              <div class="finance-label">收入</div>
              <div class="finance-value is-income">¥{{ formatMoney(monthFinance.income, true) }}</div>
              <div class="kpi-change" :style="{ color: changeColor(monthFinance.income_change) }">
                {{ changeLabel(monthFinance.income_change) }}
              </div>
            </div>
          </div>

          <div v-if="financeCats.length > 0" class="finance-cats">
            <div class="finance-cats-title">分类占比</div>
            <div v-for="c in financeCats" :key="c.name" class="finance-cat-row">
              <span class="finance-cat-dot" :style="{ background: c.color }" />
              <span class="finance-cat-name">{{ c.name }}</span>
              <span class="finance-cat-value">¥{{ formatMoney(c.value, true) }}</span>
              <span class="finance-cat-pct">{{ c.pct }}%</span>
            </div>
          </div>
        </template>
        <div v-else class="panel-empty">
          <Icon name="FolderOpen" :size="32" class="empty-emoji" aria-hidden="true" />
          <span>暂无财务数据</span>
        </div>
      </section>

      <!-- ⑥.5 重要日子（纪念日 / 倒数日）
           位置按 spec 06 §2：本月财务之下、快捷操作之上。
           ⚠️ 一条都没有时组件内部整卡不渲染，这里不额外判空。 -->
      <AnniversaryCard />

      <!-- ⑦ 快捷入口 -->
      <section class="quick-grid">
        <button
          v-for="q in quickItems"
          :key="q.key"
          type="button"
          class="quick-item"
          :style="{ background: q.bg, color: q.color }"
          @click="q.onClick"
        >
          <Icon :name="q.icon" :size="24" aria-hidden="true" />
          <span class="quick-label">{{ q.label }}</span>
        </button>
      </section>

      <!-- 整体加载失败（与「暂无数据」区分） -->
      <div v-if="homeError && !home" class="global-error">
        <span>首页数据加载失败，请检查网络后重试</span>
        <button type="button" class="retry-btn" @click="refresh">重试</button>
      </div>
    </main>

    <!-- 记一笔弹层（从首页 + 唤起） -->
    <TransactionEditSheet
      v-model:show="txSheetShow"
      :accounts="accounts"
      :on-save="onQuickTxSave"
    />
  </div>
</template>

<style lang="scss" scoped>
.home-page {
  /* ⚠️ 这里**不写** height：高度由 HomeLayout 的 .content 用 flex 直接分配
     （flex:1 1 0% + min-height:0），不经过百分比解析，也不与布局层的定位
     方案在同一组属性上争抢（详见 HomeLayout .content 的注释）。
     历史坑：之前写 height:100%，而 .content 用 `position:absolute; inset:0`
     钉页面根 —— 两条规则特异性相同，本文件的样式在 HomeLayout 之后注入，
     于是 `position:relative`（.fab 的定位容器需要）静默胜出，absolute 被
     架空，高度退回依赖百分比解析（iOS 上不可靠）→ 页面被内容撑高 →
     .home-body 的 flex:1 空转 → 滚动传到根、顶部栏与胶囊一起弹。 */
  background: var(--color-bg-app);
  display: flex;
  flex-direction: column;
}

/* ========== Header ==========
   顶部栏（头像 + 问候语 + 日期）不在本页渲染了：
   → HomeLayout 的 components/PageHeader.vue（hero 变体）
   本页只保留滚动容器 .home-body。 */

.home-body {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  /* 滚到两端不把滚动链传给父级，避免 iOS 上整个视口跟着弹动 */
  overscroll-behavior-y: contain;
  /* 底部留白统一走令牌（底距 + 胶囊高 + 呼吸位），离开胶囊不会贴住 */
  padding: 16px var(--space-5) var(--tabbar-reserve, 83px);
}

/* ========== 通用卡片 ========== */
.card {
  background: var(--color-bg-card);
  border-radius: 16px;
  box-shadow: var(--shadow-xs);
  padding: 14px 16px;
  margin-bottom: 16px;
}
.mood-card { padding: 14px 16px; }

.card-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 10px;
}
.card-title {
  /* 小标题令牌：与记录/统计/账户等模块的卡片标题统一（原为 15px，
     其余模块都是 --fs-h4 16px） */
  font-size: var(--fs-h4);
  font-weight: 600;
  color: var(--color-text-primary);
  margin: 0;
}
.card-sub {
  font-size: var(--fs-micro);
  font-family: var(--font-num);
  color: var(--color-text-tertiary);
}
.card-more {
  background: transparent;
  border: 0;
  padding: 0;
  font-size: var(--fs-caption-sm);
  color: var(--color-text-tertiary);
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
}

/* ========== KPI（2×2） ========== */
.kpi-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 10px;
  margin-bottom: 16px;
}
.kpi-card {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 12px;
  background: var(--color-bg-card);
  border: 0;
  border-radius: 14px;
  box-shadow: var(--shadow-xs);
  text-align: left;
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  &:active { transform: scale(0.98); }
}
.kpi-head {
  display: flex;
  align-items: center;
  gap: 6px;
}
.kpi-emoji {
  width: 24px;
  height: 24px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 7px;
  line-height: 1;
  flex-shrink: 0;
}
.kpi-label {
  font-size: var(--fs-caption-sm);
  color: var(--color-text-tertiary);
}
.kpi-value {
  /* 数值阶令牌：与待办 / 统计 / 记录·习惯卡的 KPI 数值同大（原为 19px，
     同一角色在待办是 17px、统计 18px、习惯卡 22px，五种大小） */
  font-size: var(--fs-metric);
  font-weight: 700;
  font-family: var(--font-num);
  line-height: 1.15;
}
.kpi-value-sub {
  /* 数值次要部分令牌：与统计页 .kpi-value-muted 统一（原为 12px） */
  font-size: var(--fs-metric-sm);
  font-weight: 500;
  color: var(--color-text-tertiary);
}
.kpi-foot {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-top: 2px;
  min-height: 14px;
}
.kpi-bar {
  flex: 1;
  height: 4px;
  background: var(--color-bg-hover);
  border-radius: 2px;
  overflow: hidden;
}
.kpi-bar-fill {
  height: 100%;
  border-radius: 2px;
  transition: width var(--duration-normal) var(--ease-default);
}
.kpi-foot-text {
  flex-shrink: 0;
  font-size: var(--fs-micro);
  font-family: var(--font-num);
  color: var(--color-text-secondary);
  &.muted { color: var(--color-text-tertiary); }
}
.kpi-change {
  font-size: var(--fs-micro);
  font-weight: 600;
  font-family: var(--font-num);
}

/* ========== 骨架 / 空态 / 错误态 ========== */
.panel-skel { display: flex; flex-direction: column; gap: 8px; }
.skel-row {
  height: 36px;
  background: linear-gradient(90deg, #F3F4F6 25%, #E5E7EB 50%, #F3F4F6 75%);
  background-size: 200% 100%;
  border-radius: 6px;
  animation: shimmer 1.5s infinite;
}
.panel-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  padding: 12px 0;
  font-size: var(--fs-caption-sm);
  color: var(--color-text-tertiary);
  .empty-emoji { opacity: 0.6; }
  .empty-desc { font-size: var(--fs-micro); }
}
.panel-error,
.global-error {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  padding: 16px 0;
  font-size: var(--fs-caption-sm);
  color: var(--color-danger-dark);
}
.retry-btn {
  height: 26px;
  padding: 0 12px;
  border: 1px solid currentColor;
  border-radius: 13px;
  background: transparent;
  color: inherit;
  font-size: var(--fs-caption-sm);
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
}

/* ========== 今日习惯 ========== */
.habit-wrap {
  display: flex;
  gap: 14px;
  align-items: flex-start;
}
.habit-ring-wrap {
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
}
.habit-ring { display: block; }
.ring-value {
  /* 数值阶令牌：环图中心数值与各模块 KPI 同大 */
  font-size: var(--fs-metric);
  font-weight: 700;
  font-family: var(--font-num);
  fill: var(--color-text-primary);
}
.ring-sub {
  font-size: var(--fs-micro);
  font-family: var(--font-num);
  fill: var(--color-text-tertiary);
}
.ring-caption {
  font-size: var(--fs-tab);
  color: var(--color-text-tertiary);
  white-space: nowrap;
}

.habit-list {
  flex: 1;
  min-width: 0;
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.habit-line {
  display: flex;
  align-items: center;
  gap: 8px;
  &.is-done .habit-name { color: var(--color-text-tertiary); }
}
.habit-emoji {
  flex-shrink: 0;
  width: 28px;
  height: 28px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 8px;
  line-height: 1;
}
.habit-body { flex: 1; min-width: 0; }
.habit-name {
  /* 小正文令牌：与记录页 .habit-title、统计页 .habit-name 统一（原为 13px，
     同名元素在统计页是 14px） */
  font-size: var(--fs-body-sm);
  font-weight: 500;
  color: var(--color-text-primary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.habit-progress-row {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-top: 3px;
}
.habit-bar {
  flex: 1;
  height: 4px;
  background: var(--color-bg-hover);
  border-radius: 2px;
  overflow: hidden;
}
.habit-bar-fill {
  height: 100%;
  border-radius: 2px;
  transition: width var(--duration-normal) var(--ease-default);
}
.habit-count {
  flex-shrink: 0;
  font-size: var(--fs-tab);
  font-family: var(--font-num);
  color: var(--color-text-tertiary);
}
.habit-check {
  flex-shrink: 0;
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--color-primary);
  color: #FFFFFF;
  border: 0;
  border-radius: 50%;
  font-size: var(--fs-h4);
  font-weight: 700;
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  &:active:not(:disabled) { transform: scale(0.9); }
  &:disabled {
    background: var(--color-success);
    cursor: default;
  }
}

/* ========== 本月财务 ========== */
.finance-summary {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 10px;
}
.finance-cell {
  padding: 10px 12px;
  background: var(--color-bg-hover);
  border-radius: 10px;
}
.finance-label {
  font-size: var(--fs-micro);
  color: var(--color-text-tertiary);
}
.finance-value {
  margin: 2px 0;
  font-size: var(--fs-h4);
  font-weight: 700;
  font-family: var(--font-num);
  &.is-expense { color: var(--color-danger-dark); }
  &.is-income { color: var(--color-success-dark); }
}
.finance-cats { margin-top: 12px; }
.finance-cats-title {
  font-size: var(--fs-micro);
  color: var(--color-text-tertiary);
  margin-bottom: 6px;
}
.finance-cat-row {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 5px 0;
  font-size: var(--fs-caption-sm);
}
.finance-cat-dot {
  flex-shrink: 0;
  width: 8px;
  height: 8px;
  border-radius: 50%;
}
.finance-cat-name {
  flex: 1;
  min-width: 0;
  color: var(--color-text-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.finance-cat-value {
  flex-shrink: 0;
  font-family: var(--font-num);
  color: var(--color-text-primary);
}
.finance-cat-pct {
  flex-shrink: 0;
  width: 36px;
  text-align: right;
  font-family: var(--font-num);
  color: var(--color-text-tertiary);
}

/* ========== 快捷入口 ========== */
.quick-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 10px;
}
.quick-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  padding: 14px 4px;
  border: 0;
  border-radius: 14px;
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  &:active { transform: scale(0.96); }
}
.quick-label {
  font-size: var(--fs-caption-sm);
  font-weight: 500;
}

@keyframes shimmer {
  0%   { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}
</style>
