// life-assisitant-ui-desktop/src/pages/me/profile.tsx
/**
 * Me / Profile sub-page
 */
import { useState, useCallback } from 'react'
import { Card, Button, Input, Toast } from '@douyinfe/semi-ui'
import { useNavigate } from 'react-router-dom'
import { useUserStore, useDisplayName } from '@/stores/user'
import UserAvatar from '@/components/UserAvatar'
import { userApi } from '@/api/user'
import { storage } from '@/utils/storage'

// 注：换头像入口在个人中心首页（头像 hover「点击上传」，D-03 第七轮）；
//     第八轮起走文件上传接口（压缩逻辑见 src/utils/avatar.ts），本页只负责展示与资料保存。
export default function MeProfilePage() {
  const navigate = useNavigate()
  const userStore = useUserStore()
  const displayName = useDisplayName()
  const user = userStore.user

  const [form, setForm] = useState({
    name: user?.name || '',
    email: user?.email || '',
  })
  const [saving, setSaving] = useState(false)

  const onSave = useCallback(async () => {
    if (!form.name.trim()) {
      Toast.error('昵称不能为空')
      return
    }
    setSaving(true)
    try {
      const updated = await userApi.updateProfile({
        name: form.name.trim(),
        email: form.email.trim() || undefined,
      })
      // 后端返回最新用户（含新 version），写回本地缓存与 store
      const freshUser = { ...userStore.user!, ...updated }
      storage.set('user', freshUser)
      useUserStore.setState({ user: freshUser })
    } catch (e) {
      // M3：失败即显式报错，不再「仅本地生效」假写。
      // 响应拦截器已 Toast 具体原因（校验 / 邮箱冲突 / 版本冲突），这里只记录。
      console.error('[profile] 保存失败', e)
    } finally {
      setSaving(false)
    }
  }, [form, userStore.user])

  return (
    <div className="sub-page">
      <div className="sub-page-header">
        <span className="back-btn" onClick={() => navigate('/me')}>‹ 返回</span>
        <h3>个人资料</h3>
      </div>

      <div className="settings-page">
        <Card bordered={false} className="card">
          <div style={{ display: 'flex', alignItems: 'center', gap: 20, marginBottom: 24 }}>
            <UserAvatar
              size="extra-large"
              className="profile-avatar-initials"
              style={{ backgroundColor: 'var(--color-primary-500)', color: 'white', fontWeight: 700 }}
            />
            <div>
              <div className="profile-display-name">{displayName}</div>
              <div style={{ color: 'var(--color-text-tertiary)', fontSize: 13 }}>{user?.username}</div>
            </div>
          </div>

          <div className="field">
            <label className="field-label">昵称</label>
            <Input
              value={form.name}
              onChange={(v: string) => setForm((f) => ({ ...f, name: v }))}
              placeholder="输入昵称"
              maxLength={30}
              showClear
            />
          </div>
          <div className="field">
            <label className="field-label">邮箱</label>
            <Input
              value={form.email}
              onChange={(v: string) => setForm((f) => ({ ...f, email: v }))}
              placeholder="输入邮箱"
              showClear
            />
          </div>

          <div style={{ marginTop: 24, display: 'flex', justifyContent: 'flex-end', gap: 12 }}>
            <Button theme="light" onClick={() => navigate('/me')}>取消</Button>
            <Button theme="solid" type="primary" loading={saving} onClick={onSave}>保存</Button>
          </div>
        </Card>
      </div>
    </div>
  )
}

// life-assisitant-ui-mobile/src/pages/me/profile.vue
<script setup lang="ts">
/**
 * 个人资料（移动端）
 *
 * SYNC-FROM-DESKTOP: life-assisitant-ui-desktop/src/pages/me/profile.tsx
 * 最后同步：2026-09-18（Phase 5.3）
 *
 * 与桌面端一致：头像只展示（换头像入口在「我的」首页点头像），本页负责资料保存。
 * 差异：保存成功后走 store 的 patchUser 落库（桌面端是直接 setState + storage.set 两步）。
 */
import { computed, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { showFailToast } from 'vant'
import { useUserStore } from '@/stores/user'
import { userApi } from '@/api/user'
import { displayNameOf } from '@/utils/avatar'
import UserAvatar from '@/components/UserAvatar.vue'

const router = useRouter()
const userStore = useUserStore()

const displayName = computed(() => displayNameOf(userStore.user))

const form = reactive({
  name: userStore.user?.name || '',
  email: userStore.user?.email || '',
})

const saving = ref(false)
const errorText = ref('')

async function onSave(): Promise<void> {
  errorText.value = ''
  const name = form.name.trim()
  if (!name) {
    errorText.value = '昵称不能为空'
    return
  }
  if (name.length < 2 || name.length > 20) {
    errorText.value = '昵称需为 2-20 个字符'
    return
  }
  const email = form.email.trim()
  if (email && !/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(email)) {
    errorText.value = '邮箱格式不正确'
    return
  }

  saving.value = true
  try {
    // 后端返回最新用户（含新 version），必须整体合并回本地 ——
    // 否则下次保存会拿旧 version 去 CAS，触发乐观锁冲突（409001）。
    const updated = await userApi.updateProfile({
      name,
      email: email || undefined,
    })
    userStore.patchUser(updated)
  } catch (e) {
    // 响应拦截器已 toast 具体原因（校验 / 邮箱冲突 / 版本冲突），这里只做兜底
    if (!(e instanceof Error && e.message)) showFailToast('保存失败，请稍后重试')
  } finally {
    saving.value = false
  }
}

function onCancel(): void {
  router.back()
}
</script>

<template>
  <div class="sub-page">
    <header class="sub-header">
      <button class="sub-back" type="button" aria-label="返回" @click="onCancel">‹</button>
      <h2 class="sub-title">个人资料</h2>
    </header>

    <main class="sub-body">
      <!-- 头像与账号概览 -->
      <section class="card profile-head">
        <UserAvatar :user="userStore.user" :size="64" />
        <div class="head-info">
          <div class="head-name">{{ displayName }}</div>
          <div class="head-account">@{{ userStore.user?.username || '-' }}</div>
          <div class="head-hint">换头像请回「我的」页点头像</div>
        </div>
      </section>

      <!-- 表单 -->
      <section class="card">
        <div class="field">
          <label class="field-label" for="pf-name">昵称</label>
          <van-field
            id="pf-name"
            v-model="form.name"
            placeholder="输入昵称"
            maxlength="20"
            clearable
            :border="false"
            class="field-input"
            :disabled="saving"
          />
          <p class="field-hint">2-20 个字符</p>
        </div>

        <div class="field">
          <label class="field-label" for="pf-email">邮箱</label>
          <van-field
            id="pf-email"
            v-model="form.email"
            type="email"
            placeholder="输入邮箱"
            clearable
            :border="false"
            class="field-input"
            :disabled="saving"
          />
          <p class="field-hint">用于登录与找回密码</p>
        </div>

        <p v-if="errorText" class="field-error">{{ errorText }}</p>
      </section>

      <!-- 操作 -->
      <div class="actions">
        <button class="btn btn-ghost" type="button" :disabled="saving" @click="onCancel">
          取消
        </button>
        <button class="btn btn-primary" type="button" :disabled="saving" @click="onSave">
          {{ saving ? '保存中…' : '保存' }}
        </button>
      </div>
    </main>
  </div>
</template>

<style lang="scss" scoped>
@use '@/styles/subpage.scss' as *;

.profile-head {
  display: flex;
  align-items: center;
  gap: var(--space-4);
}
.head-info { flex: 1; min-width: 0; }
.head-name {
  font-size: var(--fs-h4);
  font-weight: 700;
  color: var(--color-text-primary);
  margin-bottom: 3px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.head-account {
  font-size: var(--fs-caption-sm);
  color: var(--color-text-tertiary);
  font-family: var(--font-num);
  margin-bottom: 4px;
}
.head-hint {
  font-size: var(--fs-micro);
  color: var(--color-text-tertiary);
}

.field-input {
  padding: 0;
  background: transparent;

  :deep(.van-field__control) {
    height: 42px;
    padding: 0 12px;
    font-size: var(--fs-body-sm);
    background: var(--color-bg-hover);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-lg);
    color: var(--color-text-primary);

    &::placeholder { color: var(--color-text-placeholder); }
  }
  :deep(.van-field__control--error) { border-color: var(--color-danger); }
}

.actions {
  display: flex;
  gap: 12px;
  margin-top: var(--space-2);

  .btn { flex: 1; }
}
</style>
