// life-assisitant-ui-desktop/src/pages/me/sync.tsx
/**
 * Me / Sync sub-page
 * M8：接入错误态；syncApi 返回 any，这里在页面侧收敛为强类型。
 */
import { useEffect, useCallback, useState } from 'react'
import { Card, Button, Tag, Table, Toast } from '@douyinfe/semi-ui'
import { useNavigate } from 'react-router-dom'
import { useSyncStore } from '@/stores/sync'
import { syncApi } from '@/api/sync'
import { Icon } from '@/components/icon'
import ErrorState from '@/components/ErrorState'
import { formatRelativeTime } from '@/utils/datetime'

type DetailStatus = 'synced' | 'pending' | 'error'

/** syncApi.status() 实际返回结构（后端 GET /sync/status） */
interface SyncStatusResp {
  last_sync_at?: string | null
  status?: 'synced' | 'syncing' | 'pending' | 'error'
  pending?: number
  details?: Record<string, { last_sync: string | null; status: DetailStatus; pending_count: number }>
}

const statusColors: Record<string, 'green' | 'blue' | 'amber' | 'red'> = {
  synced: 'green',
  syncing: 'blue',
  pending: 'amber',
  error: 'red',
}

const statusLabels: Record<string, string> = {
  synced: '已同步',
  syncing: '同步中',
  pending: '待同步',
  error: '同步失败',
}

export default function MeSyncPage() {
  const navigate = useNavigate()
  const syncStore = useSyncStore()
  const { status } = syncStore
  const [error, setError] = useState('')

  /**
   * 页面级拉取：store.fetch 的 catch 静默吞错并保留初始「已同步」，
   * 断网会误导为「已同步」。这里直接调 syncApi.status 以便如实暴露错误（M8）。
   */
  const fetchStatus = useCallback(async () => {
    setError('')
    useSyncStore.setState({ loading: true })
    try {
      const res = (await syncApi.status()) as SyncStatusResp
      useSyncStore.setState({
        loading: false,
        status: {
          lastSyncAt: res.last_sync_at ?? null,
          status: res.status ?? 'synced',
          pending: res.pending ?? 0,
          details: res.details ?? {},
        },
      })
    } catch {
      useSyncStore.setState({ loading: false })
      setError('同步状态加载失败，请重试')
    }
  }, [])

  useEffect(() => {
    fetchStatus()
  }, [fetchStatus])

  const onSync = async () => {
    Toast.info('开始同步...')
    await syncStore.syncNow()
    if (useSyncStore.getState().status.status === 'synced') {
      Toast.success('同步完成')
    } else if (useSyncStore.getState().status.status === 'error') {
      Toast.error('同步失败，请重试')
    }
  }

  const detailRows = Object.entries(status.details).map(([key, val]) => ({
    key,
    module: key,
    last_sync: formatRelativeTime(val.last_sync),
    status: val.status,
    pending_count: val.pending_count ?? 0,
  }))

  const columns = [
    { title: '模块', dataIndex: 'module', key: 'module' },
    { title: '最后同步', dataIndex: 'last_sync', key: 'last_sync' },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      render: (s: string) => <Tag color={statusColors[s] || 'green'}>{statusLabels[s] || s}</Tag>,
    },
    { title: '待处理', dataIndex: 'pending_count', key: 'pending_count' },
  ]

  return (
    <div className="sub-page">
      <div className="sub-page-header">
        <span className="back-btn" onClick={() => navigate('/me')}>‹ 返回</span>
        <h3>同步状态</h3>
      </div>

      <div className="settings-page">
        <Card bordered={false} className="card">
          {error ? (
            <ErrorState message={error} onRetry={fetchStatus} />
          ) : (
            <>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
                <div>
                  <div style={{ fontSize: 13, color: 'var(--color-text-tertiary)' }}>最后同步</div>
                  <div style={{ fontSize: 16, fontWeight: 700, marginTop: 4 }}>{formatRelativeTime(status.lastSyncAt)}</div>
                </div>
                <Tag color={statusColors[status.status] || 'green'} size="large">{statusLabels[status.status]}</Tag>
              </div>

              {status.pending > 0 && (
                <div style={{ marginBottom: 16, padding: '10px 14px', borderRadius: 8, background: 'var(--tint-warning-bg)', color: 'var(--tint-warning-fg)', fontSize: 13 }}>
                  <Icon name="Hourglass" size={14} style={{ marginRight: 4 }} />有 {status.pending} 条数据待同步
                </div>
              )}

              <Button block theme="solid" type="primary" loading={status.status === 'syncing'} onClick={onSync}>
                立即同步
              </Button>

              {detailRows.length > 0 && (
                <div style={{ marginTop: 24 }}>
                  <h4 style={{ marginBottom: 12, fontWeight: 700 }}>模块详情</h4>
                  <Table columns={columns as any} dataSource={detailRows} pagination={false} size="small" />
                </div>
              )}
            </>
          )}
        </Card>
      </div>
    </div>
  )
}

// life-assisitant-ui-mobile/src/pages/me/sync.vue
<script setup lang="ts">
/**
 * 同步状态（移动端）
 *
 * SYNC-FROM-DESKTOP: life-assisitant-ui-desktop/src/pages/me/sync.tsx
 * 最后同步：2026-09-18（Phase 5.6）
 *
 * 桌面端为了拿真实错误，页面里绕过 store 直接调 syncApi.status（见其注释）；
 * 移动端的 sync store 已把 error 收进 store，页面直接用即可 —— 行为等价、
 * 少一次重复请求。
 */
import { computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { showFailToast, showSuccessToast, showToast } from 'vant'
import { useSyncStore } from '@/stores/sync'
import { useUserStore } from '@/stores/user'
import { formatRelativeTime } from '@/utils/date'
import { getTint } from '@/utils/tint'
import Icon from '@/components/icon/Icon.vue'

const router = useRouter()
const syncStore = useSyncStore()
const userStore = useUserStore()

/** 同步状态 → 展示文案与 tint */
const STATUS_META: Record<string, { label: string; tint: 'success' | 'warning' | 'danger' | 'primary' }> = {
  synced: { label: '已同步', tint: 'success' },
  syncing: { label: '同步中', tint: 'primary' },
  pending: { label: '待同步', tint: 'warning' },
  error: { label: '同步失败', tint: 'danger' },
}

const cur = computed(() => STATUS_META[syncStore.status.status] ?? STATUS_META.synced)
const curTint = computed(() => getTint(cur.value.tint))

/**
 * 相对时间：空值显示「从未」。
 * utils/date 的 formatRelativeTime 对空值返回空串（它要兼顾列表场景），
 * 而同步状态页需要明确表达「从未同步过」。
 */
function relTime(iso?: string | null): string {
  return formatRelativeTime(iso) || '从未'
}

/** 详情行：模块名 + 最后同步 + 状态 + 待处理数 */
const detailRows = computed(() =>
  Object.entries(syncStore.status.details).map(([key, val]) => ({
    key,
    module: key,
    lastSync: relTime(val.last_sync),
    status: val.status ?? 'synced',
    pending: val.pending_count ?? 0,
  }))
)

function statusTint(s: string) {
  return getTint(STATUS_META[s]?.tint ?? 'neutral')
}
function statusLabel(s: string): string {
  return STATUS_META[s]?.label ?? s
}

async function onSync(): Promise<void> {
  showToast({ message: '开始同步…', duration: 1500 })
  const ok = await syncStore.syncNow()
  if (ok) showSuccessToast('同步完成')
  else showFailToast('同步失败，请重试')
}

onMounted(() => {
  void syncStore.fetch()
})
</script>

<template>
  <div class="sub-page">
    <header class="sub-header">
      <button class="sub-back" type="button" aria-label="返回" @click="router.back()">‹</button>
      <h2 class="sub-title">同步状态</h2>
    </header>

    <main class="sub-body">
      <!-- 错误态 -->
      <section v-if="syncStore.error" class="card">
        <div class="state-error">
          <span>{{ syncStore.error }}</span>
          <button class="retry-btn" type="button" @click="syncStore.fetch()">重试</button>
        </div>
      </section>

      <template v-else>
        <!-- 总览 -->
        <section class="card">
          <div class="sync-head">
            <div>
              <div class="sync-label">最后同步</div>
              <div class="sync-value">{{ relTime(syncStore.status.lastSyncAt) }}</div>
            </div>
            <span
              class="badge"
              :style="{ background: curTint.bg, color: curTint.fg }"
            >
              {{ cur.label }}
            </span>
          </div>

          <div v-if="syncStore.status.pending > 0" class="pending-hint">
            <Icon name="Hourglass" :size="16" />
            <span>有 {{ syncStore.status.pending }} 条数据待同步</span>
          </div>

          <div class="account-line">
            <span class="row-sub">同步账号：{{ userStore.user?.email || userStore.user?.username || '-' }}</span>
          </div>

          <button
            class="btn btn-primary"
            type="button"
            :disabled="syncStore.loading || syncStore.status.status === 'syncing'"
            @click="onSync"
          >
            {{ syncStore.status.status === 'syncing' ? '同步中…' : '立即同步' }}
          </button>
        </section>

        <!-- 模块详情 -->
        <section class="card">
          <h3 class="card-title">模块详情</h3>
          <div v-if="syncStore.loading" class="skeleton" />
          <div v-else-if="detailRows.length === 0" class="state-empty">
            <Icon name="Package" :size="32" class="state-emoji" />
            <p class="state-text">暂无模块同步信息</p>
          </div>
          <div v-else>
            <div v-for="r in detailRows" :key="r.key" class="row">
              <span class="row-body">
                <span class="row-label">{{ r.module }}</span>
                <span class="row-sub">最后同步：{{ r.lastSync }}</span>
              </span>
              <span class="row-right">
                <span
                  class="badge"
                  :style="{ background: statusTint(r.status).bg, color: statusTint(r.status).fg }"
                >
                  {{ statusLabel(r.status) }}
                </span>
                <span v-if="r.pending > 0" class="row-sub pending-num">待处理 {{ r.pending }}</span>
              </span>
            </div>
          </div>
        </section>
      </template>
    </main>
  </div>
</template>

<style lang="scss" scoped>
@use '@/styles/subpage.scss' as *;

.sync-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: var(--space-4);
}
.sync-label {
  font-size: var(--fs-caption-sm);
  color: var(--color-text-tertiary);
}
.sync-value {
  margin-top: 4px;
  font-size: var(--fs-h4);
  font-weight: 700;
  color: var(--color-text-primary);
  font-family: var(--font-num);
}
.pending-hint {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 10px 14px;
  margin-bottom: var(--space-4);
  border-radius: var(--radius-lg);
  background: var(--tint-warning-bg);
  color: var(--tint-warning-fg);
  font-size: var(--fs-caption-sm);
}
.account-line {
  margin-bottom: var(--space-4);
}
.row-right {
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 4px;
}
.pending-num { margin-top: 0; }
</style>
