// life-assisitant-ui-mobile/src/components/HabitHeatmap.vue
<script setup lang="ts">
/**
 * HabitHeatmap —— 当月习惯打卡日历热力图（移动端）
 *
 * SYNC-FROM-DESKTOP: life-assisitant-ui-desktop/src/pages/record/components/HabitHeatmap.tsx
 * SYNC-FROM-BACKEND: life-assisitant-api/internal/model/dto/stats.go（HabitHeatmapItem）
 * 依赖：chinese-days@^1.5.9（农历 / 节气 / 法定节假日 / 调休，与桌面端同版本）
 * 最后同步：2026-09-18（Phase 3.3）
 *
 * 7 列（周一~周日）× 最多 6 行，连续格子，热度沿用 `utils/heatmap` 的绿色阶。
 * 每格显示：公历日、农历日或节气、节假日名、调休「班」标。
 *
 * ⚠️ 与桌面端的差异（交互层，不是视觉）：
 *   桌面端用 Semi Tooltip 悬浮展示某日详情；移动端没有 hover，
 *   改为**点击格子**后在日历下方固定展示该日详情行。
 *
 * ⚠️ hex 字面量刻意保留（与桌面端同因）：格子底色来自固定绿色阶
 *   （顺序色阶不随主题翻转），格内文字/边框必须与「浅底」保持对比，
 *   不能跟页面主题联动 —— 详见桌面端同文件头部注释。
 */
import { computed, ref } from 'vue'
import {
  getLunarDatesInRange,
  getSolarTerms,
  getDayDetail,
  isWorkday,
} from 'chinese-days'
import type { HabitHeatmapItem } from '@/api/types'
import { heatColor } from '@/utils/heatmap'
import { todayDate } from '@/utils/date'

const props = defineProps<{
  data: HabitHeatmapItem[]
  year: number
  /** 1-12 */
  month: number
}>()

const WEEK_HEADERS = ['一', '二', '三', '四', '五', '六', '日']

interface DayCell {
  date: string
  day: number
  inMonth: boolean
  isWeekend: boolean
  lunarDay: string
  solarTerm: string
  holidayName: string
  isHoliday: boolean
  isWorkdayInLieu: boolean
  ratio: number
  completed: number
  total: number
}

/** 点击选中的日期（移动端替代 Tooltip） */
const selectedDate = ref('')

const cells = computed<DayCell[]>(() => {
  const year = props.year
  const month = props.month
  const daysInMonth = new Date(year, month, 0).getDate()
  const firstWeekDay = new Date(year, month - 1, 1).getDay()
  const firstCol = (firstWeekDay + 6) % 7 // 周一=0 … 周日=6

  const lastOffset = firstCol + daysInMonth - 1
  const rows = Math.min(6, Math.max(4, Math.ceil((lastOffset + 1) / 7)))
  const totalCells = rows * 7
  const result: DayCell[] = []

  const dataMap = new Map<string, HabitHeatmapItem>()
  for (const d of props.data) dataMap.set(d.date, d)

  // 农历 / 节气范围：网格首日 → 网格末日
  const gridStart = new Date(year, month - 1, 1 - firstCol)
  const gridEnd = new Date(year, month - 1, 1 - firstCol + totalCells)

  const lunarMap = new Map<string, string>()
  for (const l of getLunarDatesInRange(gridStart, gridEnd)) {
    lunarMap.set(l.date, l.lunarDayCN)
  }
  const termMap = new Map<string, string>()
  for (const t of getSolarTerms(gridStart, gridEnd)) {
    termMap.set(t.date, t.name)
  }

  for (let i = 0; i < totalCells; i++) {
    const col = i % 7
    const row = Math.floor(i / 7)
    const dayOffset = row * 7 + col - firstCol
    const dateObj = new Date(year, month - 1, 1 + dayOffset)
    const y = dateObj.getFullYear()
    const m = dateObj.getMonth() + 1
    const d = dateObj.getDate()
    const dateStr = `${y}-${pad(m)}-${pad(d)}`

    const inMonth = 1 + dayOffset >= 1 && 1 + dayOffset <= daysInMonth
    const weekDayIdx = dateObj.getDay()
    const isWeekend = weekDayIdx === 0 || weekDayIdx === 6

    let holidayName = ''
    let isHoliday = false
    let isWorkdayInLieu = false
    if (inMonth) {
      const detail = getDayDetail(dateStr)
      if (detail.work === false) {
        // 法定节假日（含假期中的周末）；name 形如 "英文名,中文名,天数" → 取倒数第二段
        const parts = (detail.name || '').split(',')
        holidayName = parts.length >= 2 ? parts[parts.length - 2] : ''
        if (holidayName) isHoliday = true
      } else if (isWeekend && isWorkday(dateStr)) {
        // 周末但被调休补班
        isWorkdayInLieu = true
      }
    }

    const item = dataMap.get(dateStr)
    const completed = item?.completed ?? 0
    const total = item?.total ?? 0

    result.push({
      date: dateStr,
      day: d,
      inMonth,
      isWeekend,
      lunarDay: lunarMap.get(dateStr) ?? '',
      solarTerm: termMap.get(dateStr) ?? '',
      holidayName,
      isHoliday,
      isWorkdayInLieu,
      ratio: total > 0 ? completed / total : 0,
      completed,
      total,
    })
  }

  return result
})

const today = computed(() => todayDate())

/** 选中日的详情（点击格子后展示在日历下方） */
const selectedCell = computed(() => cells.value.find((c) => c.date === selectedDate.value) ?? null)

function onCellClick(c: DayCell): void {
  if (!c.inMonth) return
  selectedDate.value = selectedDate.value === c.date ? '' : c.date
}

/** 格内数字颜色：热力深绿底用白色，浅底用灰/主文本色 */
function dayNumColor(c: DayCell): string {
  if (c.ratio >= 0.5 && c.inMonth) return '#FFFFFF'
  if (c.isWeekend && c.inMonth && !c.isHoliday) return '#9CA3AF'
  return 'var(--color-text-primary)'
}

function lunarColor(c: DayCell): string {
  return c.ratio >= 0.5 ? '#FFFFFF' : '#9CA3AF'
}

function cellBg(c: DayCell): string {
  if (!c.inMonth) return 'transparent'
  // 周末且当月（非法定节假日）灰底；法定节假日不灰，用热度色 + 红字
  if (c.isWeekend && !c.isHoliday) return '#F9FAFB'
  return heatColor(c.ratio)
}

function pad(n: number): string {
  return String(n).padStart(2, '0')
}
</script>

<template>
  <div class="habit-calendar">
    <!-- 星期表头 -->
    <div class="cal-week">
      <div
        v-for="(w, i) in WEEK_HEADERS"
        :key="w"
        class="cal-week-cell"
        :class="{ 'is-weekend': i >= 5 }"
      >{{ w }}</div>
    </div>

    <!-- 日期网格 -->
    <div class="cal-grid">
      <button
        v-for="c in cells"
        :key="c.date"
        type="button"
        class="cal-cell"
        :class="{
          'is-out': !c.inMonth,
          'is-today': c.date === today,
          'is-selected': c.date === selectedDate,
        }"
        :style="{
          background: cellBg(c),
          borderColor: c.date === today ? '#3B82F6' : 'transparent',
        }"
        @click="onCellClick(c)"
      >
        <span class="cell-day" :style="{ color: dayNumColor(c) }">{{ c.inMonth ? c.day : '' }}</span>

        <span class="cell-sub">
          <span v-if="c.solarTerm" class="sub-term">{{ c.solarTerm }}</span>
          <span v-else-if="c.lunarDay && c.inMonth" class="sub-lunar" :style="{ color: lunarColor(c) }">
            {{ c.lunarDay }}
          </span>
          <span v-if="c.isHoliday && c.holidayName" class="sub-holiday">{{ c.holidayName }}</span>
          <span v-if="c.isWorkdayInLieu" class="sub-holiday">班</span>
        </span>

        <!-- 完成度小点（有数据时才显示） -->
        <span
          v-if="c.inMonth && c.total > 0"
          class="cell-dot"
          :style="{ background: c.ratio >= 0.5 ? 'rgba(255,255,255,0.9)' : '#10B981' }"
        />
      </button>
    </div>

    <!-- 图例 -->
    <div class="cal-legend">
      <span class="legend-text">少</span>
      <span
        v-for="r in [0, 0.25, 0.5, 0.75, 1]"
        :key="r"
        class="legend-box"
        :style="{ background: heatColor(r) }"
      />
      <span class="legend-text">多</span>
      <span class="legend-hint">周末灰色 · 节气绿色 · 节日红色</span>
    </div>

    <!-- 选中日详情（移动端替代桌面端 Tooltip） -->
    <div v-if="selectedCell" class="cal-detail">
      <span class="detail-date">{{ selectedCell.date }}</span>
      <span class="detail-main">
        完成 <b>{{ selectedCell.completed }}</b> / {{ selectedCell.total }}
      </span>
      <span v-if="selectedCell.solarTerm" class="detail-tag">{{ selectedCell.solarTerm }}</span>
      <span v-if="selectedCell.holidayName" class="detail-tag is-holiday">{{ selectedCell.holidayName }}</span>
      <span v-if="selectedCell.isWorkdayInLieu" class="detail-tag is-holiday">调休上班</span>
      <span v-if="selectedCell.lunarDay" class="detail-lunar">农历 {{ selectedCell.lunarDay }}</span>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.habit-calendar {
  width: 100%;
}

/* 星期表头 */
.cal-week {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  margin-bottom: 6px;
}
.cal-week-cell {
  text-align: center;
  padding: 4px 0;
  font-size: var(--fs-micro);
  font-weight: 600;
  color: var(--color-text-secondary);
  &.is-weekend { color: #9CA3AF; }
}

/* 网格 */
.cal-grid {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 4px;
}
.cal-cell {
  position: relative;
  min-height: 52px;
  padding: 4px;
  display: flex;
  flex-direction: column;
  border: 1.5px solid transparent;
  border-radius: 8px;
  background: transparent;
  text-align: left;
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  transition: transform var(--duration-fast) var(--ease-default);
  &:active { transform: scale(0.96); }
  &.is-out { opacity: 0.35; cursor: default; }
  &.is-today { border-width: 2px; }
  &.is-selected { box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.35); }
}
.cell-day {
  font-size: var(--fs-caption-sm);
  font-weight: 600;
  line-height: 1.1;
}
.cell-sub {
  display: flex;
  flex-direction: column;
  gap: 1px;
  margin-top: 2px;
  font-size: var(--fs-nano);
  line-height: 1.25;
}
.sub-term {
  color: #059669;
  font-weight: 600;
}
.sub-lunar { color: #9CA3AF; }
.sub-holiday {
  color: #DC2626;
  font-weight: 600;
}
.cell-dot {
  position: absolute;
  right: 4px;
  bottom: 4px;
  width: 4px;
  height: 4px;
  border-radius: 50%;
}

/* 图例 */
.cal-legend {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: 10px;
}
.legend-text {
  font-size: var(--fs-tab);
  color: #9CA3AF;
}
.legend-box {
  width: 12px;
  height: 12px;
  border-radius: 3px;
}
.legend-hint {
  margin-left: 8px;
  font-size: var(--fs-tab);
  color: #9CA3AF;
}

/* 选中日详情 */
.cal-detail {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 10px;
  padding: 8px 10px;
  background: var(--color-bg-hover);
  border-radius: 8px;
  font-size: var(--fs-caption-sm);
  color: var(--color-text-secondary);
}
.detail-date {
  font-family: var(--font-num);
  font-weight: 600;
  color: var(--color-text-primary);
}
.detail-main b {
  color: var(--color-success-dark);
  font-family: var(--font-num);
}
.detail-tag {
  padding: 1px 6px;
  border-radius: 4px;
  background: var(--color-success-light);
  color: var(--color-success-dark);
  font-size: var(--fs-tab);
  font-weight: 600;
  &.is-holiday {
    background: var(--color-danger-light);
    color: var(--color-danger-dark);
  }
}
.detail-lunar {
  font-size: var(--fs-tab);
  color: var(--color-text-tertiary);
}
</style>

// life-assisitant-ui-desktop/src/pages/record/components/HabitHeatmap.tsx
/**
 * HabitHeatmap — 当月习惯打卡日历热力图
 * 7 列（周一~周日）× 最多 6 行，连续格子，热度沿用绿色色阶
 * 每个格子显示：几号（公历）、农历日、节气、节假日/调休标识
 * 周六日格子灰色；法定节假日/调休标红；节气标绿
 *
 * ⚠️ 本文件中的 hex 字面量（含 A07 §4.2 点名的 `#3B82F6` / `#DC2626`）
 * 是**刻意保留**的，不是漏改：
 *
 *   格子的底色来自 `@/utils/heatmap` 的固定绿色阶（见该文件说明——顺序色阶
 *   不随主题翻转），因此**即使暗色主题下格子仍是浅底**。格内文字/边框必须与
 *   「浅底」保持对比，而不能与页面主题联动：
 *
 *     #9CA3AF  周末数字 / 农历日   → 换成 --color-text-tertiary 会在暗色下
 *                                   变浅（#9CA3AF 恰好同值）而在亮色下变深，
 *                                   与相邻格子不一致
 *     #3B82F6  今日格子外框        → 换成 --color-primary-500 会在暗色下变
 *                                   成 #5B9DFF 浅蓝，压在浅底上几乎看不见
 *     #DC2626  节气/节假日/「班」  → 换成 --color-danger 会在暗色下变成
 *                                   #F87171 浅红，同样压不住浅底
 *
 * 图例（「少 / 多 / 周末灰色…」那一行）在页面背景上，不受此限，如需令牌化
 * 应只改那一处。 —— 若后续把色阶改为主题联动，则本文件的字面量应同步令牌化。
 */
import { useMemo } from 'react'
import { Tooltip } from '@douyinfe/semi-ui'
import {
  getLunarDatesInRange,
  getSolarTerms,
  getDayDetail,
  isWorkday,
} from 'chinese-days'
import type { HabitHeatmapItem } from '@/api/types'
import { heatColor } from '@/utils/heatmap'

interface Props {
  data: HabitHeatmapItem[]
  year: number
  month: number // 1-12
}

const WEEK_HEADERS = ['一', '二', '三', '四', '五', '六', '日']

interface DayCell {
  date: string        // YYYY-MM-DD
  day: number         // 几号（公历）
  weekDay: number     // 0=周一 ... 6=周日
  inMonth: boolean    // 是否本月
  isWeekend: boolean  // 周六/周日
  lunarDay: string    // 农历日，如 "十九"、"初一"
  solarTerm: string   // 节气名（空表示无）
  holidayName: string // 节假日名（空表示无）
  isHoliday: boolean  // 法定节假日（含调休放假）
  isWorkdayInLieu: boolean // 调休补班日（本周末却要上班）
  ratio: number       // 完成率 0~1
  completed: number
  total: number
}

export function HabitHeatmap({ data, year, month }: Props) {
  const cells = useMemo<DayCell[]>(() => {
    // 当月天数
    const daysInMonth = new Date(year, month, 0).getDate()
    // 当月 1 号是星期几（0=周日, 1=周一 ... 6=周六）
    const firstWeekDay = new Date(year, month - 1, 1).getDay() // 0=周日
    // 转成周一=0 的索引
    const firstCol = (firstWeekDay + 6) % 7 // 周一=0 ... 周日=6

    // 构建网格：动态行数（含该月最后一天所在行），最多 6 行
    const lastOffset = firstCol + daysInMonth - 1
    const rows = Math.min(6, Math.max(4, Math.ceil((lastOffset + 1) / 7)))
    const totalCells = rows * 7
    const result: DayCell[] = []

    // 打卡数据 map
    const dataMap = new Map<string, HabitHeatmapItem>()
    for (const d of data) dataMap.set(d.date, d)

    // 农历范围：从网格第一天到网格最后一天
    const gridStart = new Date(year, month - 1, 1 - firstCol)
    const gridEnd = new Date(year, month - 1, 1 - firstCol + totalCells)
    const lunarList = getLunarDatesInRange(gridStart, gridEnd)
    const lunarMap = new Map<string, string>()
    for (const l of lunarList) lunarMap.set(l.date, l.lunarDayCN)

    // 节气
    const terms = getSolarTerms(gridStart, gridEnd)
    const termMap = new Map<string, string>()
    for (const t of terms) termMap.set(t.date, t.name)

    for (let i = 0; i < totalCells; i++) {
      const col = i % 7
      const row = Math.floor(i / 7)
      const dayOffset = row * 7 + col - firstCol // 相对 1 号的偏移
      const dateObj = new Date(year, month - 1, 1 + dayOffset)
      const y = dateObj.getFullYear()
      const m = dateObj.getMonth() + 1
      const d = dateObj.getDate()
      const dateStr = `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`

      const inMonth = (1 + dayOffset) >= 1 && (1 + dayOffset) <= daysInMonth
      const weekDayIdx = dateObj.getDay() // 0=周日
      const isWeekend = weekDayIdx === 0 || weekDayIdx === 6

      // 节假日/调休
      let holidayName = ''
      let isHoliday = false
      let isWorkdayInLieu = false
      if (inMonth) {
        const detail = getDayDetail(dateStr)
        if (detail.work === false) {
          // 法定节假日（含假期中的周末，如国庆 10/3、10/4）；name 格式 "英文名,中文名,天数" → 取倒数第二段中文名
          const parts = (detail.name || '').split(',')
          holidayName = parts.length >= 2 ? parts[parts.length - 2] : ''
          if (holidayName) isHoliday = true
        } else if (isWeekend && isWorkday(dateStr)) {
          // 周末但被调休补班
          isWorkdayInLieu = true
        }
        // 注意：调休补班日（如国庆 10/10 周六）work=true，name 虽含"国庆节"但不标节日，走上面的 isWorkdayInLieu 标"班"
      }

      // 完成率
      const item = dataMap.get(dateStr)
      const completed = item?.completed ?? 0
      const total = item?.total ?? 0
      const ratio = total > 0 ? completed / total : 0

      result.push({
        date: dateStr,
        day: d,
        weekDay: weekDayIdx,
        inMonth,
        isWeekend,
        lunarDay: lunarMap.get(dateStr) ?? '',
        solarTerm: termMap.get(dateStr) ?? '',
        holidayName,
        isHoliday,
        isWorkdayInLieu,
        ratio,
        completed,
        total,
      })
    }

    return result
  }, [data, year, month])

  const todayStr = useMemo(() => {
    const n = new Date()
    return `${n.getFullYear()}-${String(n.getMonth() + 1).padStart(2, '0')}-${String(n.getDate()).padStart(2, '0')}`
  }, [])

  return (
    <div className="habit-calendar" style={{ width: '50%' }}>
      {/* 表头 */}
      <div className="habit-cal-week" style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', marginBottom: 8 }}>
        {WEEK_HEADERS.map((w, i) => (
          <div
            key={w}
            style={{
              textAlign: 'center',
              fontSize: 12,
              fontWeight: 600,
              color: i >= 5 ? '#9CA3AF' : 'var(--color-text-secondary)',
              padding: '4px 0',
            }}
          >
            {w}
          </div>
        ))}
      </div>

      {/* 格子网格 */}
      <div className="habit-cal-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 6 }}>
        {cells.map((c) => {
          const isToday = c.date === todayStr
          const bg = c.inMonth ? heatColor(c.ratio) : 'transparent'
          // 周末且当月（非法定节假日）：灰色底；法定节假日不灰，用热度色，红色文字标识
          const cellBg = c.isWeekend && c.inMonth && !c.isHoliday ? '#F9FAFB' : bg
          // 热力深绿色背景上的农历文字用白色，浅色背景用灰色
          const lunarColor = c.inMonth && c.ratio >= 0.5 ? '#FFFFFF' : '#9CA3AF'

          const cell = (
            <div
              style={{
                position: 'relative',
                minHeight: 64,
                borderRadius: 8,
                padding: 4,
                background: cellBg,
                opacity: c.inMonth ? 1 : 0.35,
                border: isToday ? '2px solid #3B82F6' : '1px solid transparent',
                display: 'flex',
                flexDirection: 'column',
                transition: 'none',
              }}
            >
              {/* 公历几号 */}
              <div
                style={{
                  fontSize: 13,
                  fontWeight: 600,
                  lineHeight: 1,
                  color: c.isWeekend && c.inMonth && !c.isHoliday ? '#9CA3AF' : 'var(--color-text-primary)',
                }}
              >
                {c.inMonth ? c.day : ''}
              </div>

              {/* 农历 / 节气 / 节假日 标识 */}
              <div style={{ marginTop: 2, fontSize: 10, lineHeight: 1.3, display: 'flex', flexDirection: 'column', gap: 1 }}>
                {c.solarTerm ? (
                  <span style={{ color: '#059669', fontWeight: 600 }}>{c.solarTerm}</span>
                ) : c.lunarDay && c.inMonth ? (
                  <span style={{ color: lunarColor }}>{c.lunarDay}</span>
                ) : null}
                {c.isHoliday && c.holidayName ? (
                  <span style={{ color: '#DC2626', fontWeight: 600 }}>{c.holidayName}</span>
                ) : null}
                {c.isWorkdayInLieu ? (
                  <span style={{ color: '#DC2626', fontWeight: 600 }}>班</span>
                ) : null}
              </div>
            </div>
          )

          // 非本月格子不挂 Tooltip，避免空白气泡
          if (!c.inMonth) {
            return <div key={c.date}>{cell}</div>
          }

          return (
            <Tooltip
              key={c.date}
              content={`${c.date} 完成 ${c.completed}/${c.total}${c.solarTerm ? ' · ' + c.solarTerm : ''}${c.holidayName ? ' · ' + c.holidayName : ''}`}
            >
              {cell}
            </Tooltip>
          )
        })}
      </div>

      {/* 图例 */}
      <div className="heatmap-legend" style={{ display: 'flex', alignItems: 'center', gap: 4, marginTop: 12 }}>
        <span style={{ fontSize: 11, color: '#9CA3AF' }}>少</span>
        {[0, 0.25, 0.5, 0.75, 1].map((r) => (
          <div key={r} style={{ width: 14, height: 14, borderRadius: 3, background: heatColor(r) }} />
        ))}
        <span style={{ fontSize: 11, color: '#9CA3AF' }}>多</span>
        <span style={{ marginLeft: 12, fontSize: 11, color: '#9CA3AF' }}>周末灰色 · 节气绿色 · 节日红色</span>
      </div>
    </div>
  )
}

export default HabitHeatmap
