// life-assisitant-ui-mobile/src/pages/me/anniversaries.vue
<script setup lang="ts">
/**
 * 重要日子（纪念日 / 倒数日）管理页（移动端）
 *
 * SYNC-FROM-DESKTOP: life-assisitant-ui-desktop/src/pages/me/anniversaries.tsx
 * 设计：md/spec-20260919-v1/06-个人中心与纪念日.md §3
 *
 * ⚠️ 分组（最近 / 本月 / 全部）**直接用后端 scope 参数拿**，前端不做二次分组 ——
 *    next_date 是后端实时推导的，前端拿 days_left 自己切会在跨月边界上错。
 *
 * ⚠️ 布局：二级页用 subpage.scss 的「固定高度 + .sub-body 单滚动容器」模型，
 *    顶部栏自绘并补 env(safe-area-inset-top)。
 */
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { showConfirmDialog } from 'vant'
import Icon from '@/components/icon/Icon.vue'
import AnniversaryEditSheet from '@/components/AnniversaryEditSheet.vue'
import { useAnniversaryStore, type AnniversaryScope } from '@/stores/anniversary'
import { categoryMeta, daysLeftText, iconOf, isToday, remindText, repeatLabel } from '@/utils/anniversary'
import { getTint } from '@/utils/tint'
import type { AnniversaryItem } from '@/api/types'

const router = useRouter()
const store = useAnniversaryStore()

const SCOPES: ReadonlyArray<{ value: AnniversaryScope; label: string }> = [
  { value: 'upcoming', label: '最近' },
  { value: 'month', label: '本月' },
  { value: 'all', label: '全部' },
]

const scope = ref<AnniversaryScope>('all')
const error = ref('')

const sheetShow = ref(false)
const editing = ref<AnniversaryItem | null>(null)

onMounted(() => {
  reload()
})

async function reload(): Promise<void> {
  error.value = ''
  try {
    await store.fetchList(scope.value)
  } catch {
    error.value = '加载失败'
  }
}

async function onScope(v: AnniversaryScope): Promise<void> {
  if (v === scope.value) return
  scope.value = v
  await reload()
}

function openCreate(): void {
  editing.value = null
  sheetShow.value = true
}

function openEdit(it: AnniversaryItem): void {
  editing.value = it
  sheetShow.value = true
}

async function onDelete(it: AnniversaryItem): Promise<void> {
  try {
    await showConfirmDialog({
      title: '删除',
      message: `确定删除「${it.title}」吗？`,
      confirmButtonText: '删除',
      cancelButtonText: '取消',
      confirmButtonColor: 'var(--color-danger)',
    })
  } catch {
    return
  }
  await store.remove(it.id)
}

const list = computed(() => store.items)

/** 某条所属 tint（配色 key 直接就是 TintName） */
function tintOf(it: AnniversaryItem) {
  return getTint(it.color || categoryMeta(it.category).color)
}
</script>

<template>
  <div class="sub-page">
    <header class="sub-header">
      <button class="sub-back" type="button" aria-label="返回" @click="router.back()">‹</button>
      <h1 class="sub-title">重要日子</h1>
      <button class="sub-right" type="button" @click="openCreate">+ 新建</button>
    </header>

    <main class="sub-body">
      <!-- 分组切换 -->
      <div class="scope-seg">
        <button
          v-for="s in SCOPES"
          :key="s.value"
          class="scope-btn"
          :class="{ 'is-on': scope === s.value }"
          type="button"
          @click="onScope(s.value)"
        >
          {{ s.label }}
        </button>
      </div>

      <!-- 加载中 -->
      <div v-if="store.loading && list.length === 0" class="skeleton" />

      <!-- 错误 -->
      <div v-else-if="error" class="state-error">
        <span>{{ error }}</span>
        <button class="retry-btn" type="button" @click="reload">重试</button>
      </div>

      <!-- 空态 -->
      <div v-else-if="list.length === 0" class="state-empty">
        <Icon name="Calendar" :size="34" class="state-icon" />
        <p class="state-text">还没有重要的日子，点右上角新建一个吧</p>
      </div>

      <!-- 列表 -->
      <div v-else class="card ann-list">
        <van-swipe-cell v-for="it in list" :key="it.id">
          <button class="ann-row" type="button" @click="openEdit(it)">
            <span class="ann-icon" :style="{ background: tintOf(it).bg, color: tintOf(it).fg }">
              <Icon :name="iconOf(it.icon, it.category)" :size="18" />
            </span>
            <span class="ann-body">
              <span class="ann-title">
                {{ it.title }}
                <Icon v-if="it.is_pinned" name="Pin" :size="12" class="ann-pin" />
              </span>
              <span class="ann-sub">
                {{ categoryMeta(it.category).label }} · {{ repeatLabel(it.repeat_rule) }} ·
                {{ remindText(it.remind_days) }}
              </span>
              <span v-if="it.note" class="ann-note">{{ it.note }}</span>
            </span>
            <span class="ann-right">
              <span class="ann-date">{{ it.next_date.slice(5).replace('-', '/') }}</span>
              <span class="ann-days" :class="{ 'is-today': isToday(it.days_left) }">
                {{ daysLeftText(it.days_left) }}
              </span>
            </span>
          </button>
          <template #right>
            <button class="ann-swipe-del" type="button" @click="onDelete(it)">删除</button>
          </template>
        </van-swipe-cell>
      </div>

      <p class="ann-foot">
        下次发生日与倒计时由服务端按「基准日 + 重复规则」实时推导，不随设备时区漂移。
      </p>
    </main>

    <AnniversaryEditSheet
      v-model:show="sheetShow"
      :item="editing"
      @saved="reload"
    />
  </div>
</template>

<style lang="scss" scoped>
@use '@/styles/subpage.scss' as *;

.scope-seg {
  display: flex;
  gap: 6px;
  padding: 3px;
  margin-bottom: var(--space-3);
  background: var(--color-bg-hover);
  border-radius: var(--radius-lg);
}
.scope-btn {
  flex: 1;
  padding: 8px 0;
  border: 0;
  border-radius: var(--radius-md);
  background: transparent;
  color: var(--color-text-secondary);
  font-size: var(--fs-caption-sm);
  font-weight: 500;
  &.is-on {
    background: var(--color-bg-card);
    color: var(--color-primary);
    font-weight: 600;
    box-shadow: var(--shadow-xs);
  }
}

.ann-list { padding: 0 var(--space-4); }

.ann-row {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 0;
  border: 0;
  background: transparent;
  text-align: left;

  & + .ann-row { border-top: 1px solid var(--color-border-light); }
  &:active { opacity: 0.7; }
}
.ann-icon {
  flex-shrink: 0;
  width: 36px;
  height: 36px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-md);
}
.ann-body {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.ann-title {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: var(--fs-body-sm);
  font-weight: 600;
  color: var(--color-text-primary);
}
.ann-pin { color: var(--color-warning); }
.ann-sub,
.ann-note {
  font-size: var(--fs-micro);
  color: var(--color-text-tertiary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.ann-right {
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 2px;
}
.ann-date {
  font-size: var(--fs-caption-sm);
  color: var(--color-text-secondary);
  font-family: var(--font-num);
}
.ann-days {
  font-size: var(--fs-micro);
  font-weight: 600;
  color: var(--color-text-tertiary);
  font-family: var(--font-num);
  &.is-today { color: var(--color-danger); }
}

.ann-swipe-del {
  height: 100%;
  padding: 0 20px;
  border: 0;
  background: var(--color-danger);
  color: #FFFFFF;
  font-size: var(--fs-body-sm);
  font-weight: 600;
}

.ann-foot {
  margin: var(--space-3) 0 0;
  font-size: var(--fs-micro);
  line-height: 1.6;
  color: var(--color-text-tertiary);
}
</style>

// life-assisitant-ui-desktop/src/pages/me/anniversaries.tsx
/**
 * 重要日子（纪念日 / 倒数日）管理页（桌面端）
 *
 * SYNC-FROM-MOBILE: life-assisitant-ui-mobile/src/pages/me/anniversaries.vue
 * 设计：md/spec-20260919-v1/06-个人中心与纪念日.md §3 / §9
 *
 * ⚠️ 分组（最近 / 本月 / 全部）**直接用后端 scope 参数拿**，前端不做二次分组 ——
 *    next_date 是后端实时推导的，前端拿 days_left 自己切会在跨月边界上错。
 *
 * ⚠️ 宽度例外：现有二级页统一 `.settings-page { max-width: 600px }`，
 *    但 600px 对纪念日列表太窄（每行要放 图标+标题+日期+重复规则+倒计时+置顶）。
 *    这里用**只属于本页**的 `.management-page`（max-width: 900px），
 *    不动 `.settings-page`（它服务已有 6 个二级页，改了会一起变）。
 */
import { useCallback, useEffect, useState } from 'react'
import { Card, Button, RadioGroup, Radio, Modal, Skeleton, Empty } from '@douyinfe/semi-ui'
import { useNavigate } from 'react-router-dom'
import { Icon, TINT_VARS } from '@/components/icon'
import type { IconName, TintName } from '@/components/icon'
import AnniversaryEditDrawer from '@/components/AnniversaryEditDrawer'
import ErrorState from '@/components/ErrorState'
import { useAnniversaryStore, type AnniversaryScope } from '@/stores/anniversary'
import {
  categoryMeta,
  daysLeftText,
  iconOf,
  isToday,
  remindText,
  repeatLabel,
} from '@/utils/anniversary'
import type { AnniversaryItem } from '@/api/types'

const SCOPES: { value: AnniversaryScope; label: string }[] = [
  { value: 'upcoming', label: '最近' },
  { value: 'month', label: '本月' },
  { value: 'all', label: '全部' },
]

export default function AnniversariesPage() {
  const navigate = useNavigate()
  const store = useAnniversaryStore()

  const [scope, setScope] = useState<AnniversaryScope>('all')
  const [error, setError] = useState('')
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [editing, setEditing] = useState<AnniversaryItem | null>(null)

  const load = useCallback(
    async (s: AnniversaryScope) => {
      setError('')
      try {
        await store.fetchList(s)
      } catch {
        setError('加载失败')
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [],
  )

  useEffect(() => {
    void load(scope)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scope])

  function openCreate() {
    setEditing(null)
    setDrawerOpen(true)
  }

  function openEdit(it: AnniversaryItem) {
    setEditing(it)
    setDrawerOpen(true)
  }

  function onDelete(it: AnniversaryItem) {
    Modal.error({
      title: '删除',
      content: `确定删除「${it.title}」吗？`,
      okText: '删除',
      cancelText: '取消',
      okButtonProps: { type: 'danger' },
      onOk: async () => {
        await store.remove(it.id)
      },
    })
  }

  const loading = store.loading && store.items.length === 0

  return (
    <div className="management-page">
      <div className="page-tipbar">
        <div>
          <h2 className="page-title">
            <Icon name="Calendar" size={22} style={{ marginRight: 8 }} />
            重要日子
          </h2>
          <span className="page-tip">纪念日 / 倒数日 —— 下次发生日与倒计时由服务端实时推导</span>
        </div>
        <div className="header-right">
          <Button theme="solid" type="primary" icon={<Icon name="PlusCircle" size={16} />} onClick={openCreate}>
            新建
          </Button>
        </div>
      </div>

      <Card bordered={false} className="card">
        <div className="ann-scope">
          <RadioGroup
            type="button"
            value={scope}
            onChange={(e: any) => setScope((e?.target?.value ?? e) as AnniversaryScope)}
          >
            {SCOPES.map((s) => (
              <Radio key={s.value} value={s.value}>
                {s.label}
              </Radio>
            ))}
          </RadioGroup>
        </div>

        {loading && (
          <div className="skeleton-wrap">
            <Skeleton>
              <Skeleton.Paragraph rows={4} />
            </Skeleton>
          </div>
        )}

        {!loading && error && <ErrorState message={error} onRetry={() => load(scope)} />}

        {!loading && !error && store.items.length === 0 && (
          <Empty
            image={<Icon name="Calendar" size={48} />}
            title="还没有重要的日子"
            description="点右上角「新建」添加一个吧"
          />
        )}

        {!loading && !error && store.items.length > 0 && (
          <div className="ann-list">
            {store.items.map((it) => {
              const meta = categoryMeta(it.category)
              const tint = TINT_VARS[(it.color || meta.color) as TintName] ?? TINT_VARS.neutral
              return (
                <div key={it.id} className={`ann-row${isToday(it.days_left) ? ' is-today' : ''}`}>
                  <span className="ann-row-icon" style={{ background: tint.bg, color: tint.fg }}>
                    <Icon name={iconOf(it.icon, it.category) as IconName} size={18} />
                  </span>

                  <div className="ann-row-body">
                    <div className="ann-row-title">
                      {it.title}
                      {it.is_pinned && <Icon name="Pin" size={12} className="ann-row-pin" />}
                    </div>
                    <div className="ann-row-sub">
                      {meta.label} · {repeatLabel(it.repeat_rule)} · {remindText(it.remind_days)}
                      {it.note ? ` · ${it.note}` : ''}
                    </div>
                  </div>

                  <div className="ann-row-right">
                    <span className="ann-row-date">{it.next_date}</span>
                    <span className={`ann-row-days${isToday(it.days_left) ? ' is-today' : ''}`}>
                      {daysLeftText(it.days_left)}
                    </span>
                  </div>

                  {/* 桌面端不做左滑删除：行尾按钮 + 二次确认 */}
                  <div className="ann-row-actions">
                    <Button size="small" theme="light" type="tertiary" onClick={() => openEdit(it)}>
                      编辑
                    </Button>
                    <Button size="small" theme="light" type="danger" onClick={() => onDelete(it)}>
                      删除
                    </Button>
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </Card>

      <div className="ann-back">
        <Button theme="light" type="tertiary" onClick={() => navigate('/me')}>
          返回个人中心
        </Button>
      </div>

      <AnniversaryEditDrawer
        visible={drawerOpen}
        item={editing}
        onClose={() => setDrawerOpen(false)}
        onSaved={() => load(scope)}
      />
    </div>
  )
}
