// life-assisitant-ui-desktop/src/pages/record/components/PeriodOverviewCard.tsx
/**
 * PeriodOverviewCard —— 周期概览卡
 *
 * 红线守卫：
 *  - confidence=insufficient：一个具体日期都不显示（用 canShowDates 拦截）
 *  - confidence=low：只显示区间（window）并灰显
 *  - 所有预测数字带「预计 / 预测」字样
 *  - 隐私遮罩（👁）开启：阶段名 / 预测文案 / 天数 / 易孕期胶囊 → 掩码，卡片高度不变
 *  - 易孕期关闭（show_fertile_window=0）：不渲染易孕/排卵信息
 */
import { Card, Button, Banner } from '@douyinfe/semi-ui'
import { Icon } from '@/components/icon'
import { usePeriodStore } from '@/stores/period'
import {
  PERIOD_PHASE_META,
  PERIOD_MASK_TEXT,
  PERIOD_ALERT_FOOTNOTE,
  periodCanShowDates,
} from '@/constants/period'
import type { PeriodPrediction } from '@/api/types'

function fmtMD(s?: string): string {
  if (!s) return '—'
  const [, m, d] = s.split('-')
  return `${Number(m)}月${Number(d)}日`
}

function fmtRange(win?: string[]): string {
  if (!win || win.length < 2) return '—'
  return `${fmtMD(win[0])}–${fmtMD(win[1])}`
}

/** 阶段进度条分段着色（月经期红 / 卵泡期蓝 / 排卵期紫 / 黄体期琥珀） */
const PHASE_TINT: Record<string, string> = {
  menstrual: 'var(--color-period)',
  follicular: 'var(--color-primary-500)',
  ovulation: 'var(--color-accent)',
  luteal: 'var(--color-warning)',
}

export default function PeriodOverviewCard({ onOpenSettings }: { onOpenSettings: () => void }) {
  const store = usePeriodStore()
  const { prediction, masked, initialized, settings } = store
  const canShow = periodCanShowDates(prediction?.confidence)
  const showFertile = (settings?.show_fertile_window ?? 1) === 1

  // ---- 引导态：从没记录过 ----
  if (!initialized) {
    return (
      <Card bordered={false} className="card period-overview">
        <div className="period-guide">
          <div className="period-guide-title">开始记录你的周期</div>
          <div className="period-guide-desc">
            记录 1–2 次经期后，就能看到排卵日、易孕期和下次经期预测。
          </div>
          <Button theme="solid" type="primary" icon={<Icon name="Droplet" size={16} />} onClick={onOpenSettings}>
            开始记录
          </Button>
        </div>
      </Card>
    )
  }

  const p = prediction as PeriodPrediction | null
  const phase = p?.current_cycle?.phase
  const phaseMeta = (phase?.key && PERIOD_PHASE_META[phase.key as keyof typeof PERIOD_PHASE_META]) || null
  const dayIndex = p?.current_cycle?.day_index ?? 0
  const estLen = p?.current_cycle?.estimated_length ?? 0
  const progressPct = estLen > 0 ? Math.min(100, Math.round((dayIndex / estLen) * 100)) : 0
  const tintColor = phase?.key ? PHASE_TINT[phase.key] : 'var(--color-border-strong)'

  // 预测下次经期文案（带「预计」）
  let nextText = '预测将在你记录后生成'
  let subText = ''
  if (p?.next_period) {
    if (canShow) {
      if (p.confidence === 'low') {
        nextText = `预计 ${fmtRange(p.next_period.window)} 来月经`
        subText = `你的周期波动较大，日期仅供参考`
      } else {
        nextText = `预计 ${fmtMD(p.next_period.date)} 来月经`
        subText = p.next_period.overdue
          ? '预测窗口已过，记录今天的实际情况即可，预测会随之更新'
          : `还有 ${p.next_period.days_until} 天`
      }
    } else {
      nextText = '再记录 1 个完整周期即可开启预测'
      subText = '用默认 28 天算出的假日期与真实预测无法区分，故暂不显示'
    }
  }

  const fertileText =
    showFertile && canShow && p?.fertile_window
      ? `易孕期 ${fmtRange([p.fertile_window.start, p.fertile_window.end])} · 峰值 ${fmtRange(p.fertile_window.peak)}`
      : ''

  return (
    <Card bordered={false} className="card period-overview">
      {/* 右上角图标组：隐私遮罩 / 预测依据（信息） / 设置 */}
      <div className="period-overview-actions">
        <Icon
          name={masked ? 'EyeOff' : 'Eye'}
          size={18}
          className="period-mask-icon"
          onClick={() => store.toggleMasked()}
        />
        <Icon name="Info" size={18} onClick={onOpenSettings} />
        <Icon name="Settings" size={18} onClick={onOpenSettings} />
      </div>

      {/* 阶段名 + 周期第 N 天 */}
      <div className="period-phase-name">
        {masked ? PERIOD_MASK_TEXT : phaseMeta?.label ?? '周期中'}
      </div>
      <div className="period-day-index">
        {masked ? PERIOD_MASK_TEXT : `周期第 ${dayIndex} 天`}
      </div>

      {/* 进度条 */}
      <div className="period-progress">
        <div className="period-progress-fill" style={{ width: `${progressPct}%`, background: tintColor }} />
      </div>

      {/* 主文案 + 副文案 */}
      <div className="period-next-main" style={{ color: p?.next_period?.overdue ? 'var(--color-text-tertiary)' : undefined }}>
        {masked ? PERIOD_MASK_TEXT : nextText}
      </div>
      {subText && (
        <div className="period-next-sub">
          {masked ? PERIOD_MASK_TEXT : subText}
        </div>
      )}

      {/* 易孕期胶囊 */}
      {fertileText && (
        <div className="period-fertile-pill" style={{ background: 'var(--color-fertile-soft)', color: 'var(--color-fertile-strong)' }}>
          {masked ? PERIOD_MASK_TEXT : fertileText}
        </div>
      )}

      {/* 异常提醒（红线 5：固定尾注） */}
      {p?.alerts && p.alerts.length > 0 && (
        <div className="period-alerts">
          <Banner
            type="warning"
            closeIcon={null}
            style={{ background: 'var(--color-warning-light)', border: 'none' }}
          >
            {p.alerts.map((a, i) => (
              <div key={i} className="period-alert-item">
                {a.text}
              </div>
            ))}
            <div className="period-alert-footnote">{PERIOD_ALERT_FOOTNOTE}</div>
          </Banner>
        </div>
      )}

      {/* 阶段说明（ⓘ 文案，放在卡底，不依赖遮罩） */}
      {phaseMeta && (
        <div className="period-phase-desc" style={{ color: 'var(--color-text-tertiary)' }}>
          {phaseMeta.desc}
        </div>
      )}
    </Card>
  )
}

// life-assisitant-ui-mobile/src/components/period/PeriodOverviewCard.vue
<script setup lang="ts">
/**
 * 周期概览卡（移动端）
 *
 * SYNC-FROM-DESKTOP: life-assisitant-ui-desktop/src/pages/record/period/components/PeriodOverviewCard.tsx
 * SYNC-FROM-BACKEND: life-assisitant-api/internal/model/dto/period.go（PeriodPrediction）
 * 契约文档：md/spec-260919/04-页面与交互设计.md §4.1 / §6
 *
 * ⚠️ 前端**不做任何预测计算**：阶段、日期、区间、置信度、原因一律渲染后端返回值。
 *
 * ⚠️ 全案最硬的一条约束（04 §6.2）：`confidence === 'insufficient'` 时
 *    **一个具体日期都不许显示**。用默认 28 天算出来的假日期和真预测长得一模一样，
 *    是最容易毁掉用户信任的地方。本组件把这条收在 `canShowDates` 一处。
 *
 * 卡片高度在遮罩开/关下保持稳定（04 §3.6）：遮罩只是把文字换成等位掩码，
 * 不隐藏整块 —— 否则「这里原本有内容」本身就成了被泄露的信息。
 */
import { computed } from 'vue'
import Icon from '@/components/icon/Icon.vue'
import { PERIOD_MASK_TEXT, periodCanShowDates, type PeriodPhaseKey } from '@/constants/period'
import { formatMonthDay } from '@/utils/date'
import type { PeriodPrediction } from '@/api/types'

const props = defineProps<{
  prediction: PeriodPrediction | null
  /** 隐私遮罩（设备级 👁 状态） */
  masked: boolean
  /** 设置里是否开启易孕期展示（show_fertile_window） */
  showFertile: boolean
}>()

const emit = defineEmits<{
  (e: 'toggle-mask'): void
  (e: 'show-info'): void
  (e: 'go-settings'): void
  (e: 'show-fertile-info'): void
}>()

/** 是否允许展示具体日期（insufficient → false） */
const canShowDates = computed(() => periodCanShowDates(props.prediction?.confidence))

const currentCycle = computed(() => props.prediction?.current_cycle ?? null)

const phaseKey = computed<PeriodPhaseKey | null>(() => currentCycle.value?.phase?.key ?? null)

/** 阶段名（遮罩时换掩码） */
const phaseLabel = computed(() => {
  if (props.masked) return PERIOD_MASK_TEXT
  return currentCycle.value?.phase?.label ?? ''
})

/** 周期第 N 天 */
const dayIndex = computed(() => currentCycle.value?.day_index ?? 0)

/** 进度条填充比例（前端只做「已过多少天」的几何换算，不参与预测） */
const progressPct = computed(() => {
  const est = currentCycle.value?.estimated_length ?? 0
  if (!est || !dayIndex.value) return 0
  return Math.max(0, Math.min(100, (dayIndex.value / est) * 100))
})

/** 阶段 → 进度条填充色（令牌，不写死 hex） */
const progressColor = computed(() => {
  switch (phaseKey.value) {
    case 'menstrual':
      return 'var(--color-period)'
    case 'ovulation':
      return 'var(--color-ovulation)'
    case 'luteal':
      return 'var(--color-warning)'
    case 'follicular':
    default:
      return 'var(--color-primary)'
  }
})

/* ==================== 文案（04 §6）==================== */

const confidence = computed(() => props.prediction?.confidence ?? 'insufficient')
const nextPeriod = computed(() => props.prediction?.next_period ?? null)

/** 主文案 */
const mainText = computed(() => {
  const pred = props.prediction
  if (!pred) return ''
  if (props.masked) return PERIOD_MASK_TEXT
  if (confidence.value === 'insufficient') {
    return dayIndex.value ? `周期第 ${dayIndex.value} 天` : '开始记录你的周期'
  }
  const np = nextPeriod.value
  if (!np || np.overdue) return '预测窗口已过'
  if (confidence.value === 'low') {
    const [lo, hi] = np.window
    return lo === hi
      ? `预计 ${formatMonthDay(lo)}来月经`
      : `预计 ${formatMonthDay(lo)}–${formatMonthDay(hi)}来月经`
  }
  return `预计 ${formatMonthDay(np.date)}来月经`
})

/** 副文案 */
const subText = computed(() => {
  const pred = props.prediction
  if (!pred) return ''
  if (props.masked) return PERIOD_MASK_TEXT
  if (confidence.value === 'insufficient') return '再记录 1 个完整周期即可开启预测'
  const np = nextPeriod.value
  if (!np || np.overdue) return '记录今天的实际情况即可，预测会随之更新'
  if (confidence.value === 'low') {
    const cycles = pred.stats?.recent_cycles ?? []
    if (cycles.length >= 2) {
      const min = Math.min(...cycles)
      const max = Math.max(...cycles)
      return `你的周期波动较大（近 ${cycles.length} 个周期 ${min}–${max} 天），日期仅供参考`
    }
    return '你的周期波动较大，日期仅供参考'
  }
  if (np.days_until <= 0) return '预计就是今天'
  if (np.days_until === 1) return '还有 1 天'
  return `还有 ${np.days_until} 天`
})

/** 数据不足时的进度点：2 格表示「需要 2 个完整周期」 */
const insufficientDots = computed(() => {
  const have = Math.min(props.prediction?.sample_size ?? 0, 2)
  return [0, 1].map((i) => i < have)
})

/** 低置信度时多一行「记体温提准确度」的引导 */
const showBbtHint = computed(
  () => !props.masked && canShowDates.value && confidence.value === 'low'
)

/* ==================== 易孕期胶囊 ==================== */

/** `YYYY-MM-DD` → `M/D` */
function md(s?: string | null): string {
  if (!s) return ''
  const [, m, d] = s.split('-')
  if (!m || !d) return s
  return `${Number(m)}/${Number(d)}`
}

const fertileText = computed(() => {
  const fw = props.prediction?.fertile_window
  if (!fw) return ''
  const peak = fw.peak?.[0] && fw.peak?.[1] ? ` · 峰值 ${md(fw.peak[0])}–${md(fw.peak[1])}` : ''
  return `易孕期 ${md(fw.start)}–${md(fw.end)}${peak}`
})

const showFertile = computed(
  () => props.showFertile && !!fertileText.value && canShowDates.value
)
</script>

<template>
  <section class="ov-card">
    <!-- ==================== 顶部：阶段 + 图标组 ==================== -->
    <div class="ov-top">
      <div class="ov-top-left">
        <span v-if="phaseLabel" class="ov-phase">{{ props.masked ? PERIOD_MASK_TEXT : phaseLabel }}</span>
        <span v-else-if="canShowDates" class="ov-phase">{{ dayIndex ? `周期第 ${dayIndex} 天` : '' }}</span>
      </div>

      <div class="ov-icons">
        <button
          class="ov-icon"
          type="button"
          :aria-label="masked ? '显示敏感内容' : '隐藏敏感内容'"
          :aria-pressed="masked"
          @click="emit('toggle-mask')"
        >
          <Icon :name="masked ? 'EyeOff' : 'Eye'" :size="18" :class="masked ? 'is-on' : ''" />
        </button>
        <button class="ov-icon" type="button" aria-label="预测依据" @click="emit('show-info')">
          <Icon name="Info" :size="18" />
        </button>
        <button class="ov-icon" type="button" aria-label="经期设置" @click="emit('go-settings')">
          <Icon name="Settings" :size="18" />
        </button>
      </div>
    </div>

    <!-- 周期第 N 天（阶段名已占位时不重复；遮罩态不显示天数） -->
    <div v-if="dayIndex && canShowDates && !masked" class="ov-day">周期第 {{ dayIndex }} 天</div>

    <!-- ==================== 进度条 ==================== -->
    <div v-if="dayIndex && canShowDates" class="ov-bar" role="img" aria-label="本周期进度">
      <div class="ov-bar-fill" :style="{ width: `${progressPct}%`, background: progressColor }" />
      <div class="ov-bar-knob" :style="{ left: `${progressPct}%` }" />
    </div>

    <!-- ==================== 主 / 副文案 ==================== -->
    <p class="ov-main" :class="{ 'is-masked': masked }">{{ mainText }}</p>
    <p class="ov-sub" :class="{ 'is-masked': masked }">{{ subText }}</p>

    <!-- 数据不足：显示「还差几个周期」的点 -->
    <div v-if="!masked && confidence === 'insufficient'" class="ov-dots" aria-hidden="true">
      <span v-for="(filled, i) in insufficientDots" :key="i" class="ov-dot" :class="{ 'is-on': filled }" />
    </div>

    <!-- 低置信度引导：记体温提准确度 -->
    <button v-if="showBbtHint" class="ov-hint-link" type="button" @click="emit('show-info')">
      可记录基础体温提高准确度 ›
    </button>

    <!-- ==================== 易孕期胶囊 ==================== -->
    <button
      v-if="showFertile"
      class="ov-fertile"
      type="button"
      @click="emit('show-fertile-info')"
    >
      <Icon name="Sparkles" :size="13" />
      <span>{{ masked ? PERIOD_MASK_TEXT : fertileText }}</span>
    </button>
  </section>
</template>

<style lang="scss" scoped>
.ov-card {
  /* 高度在遮罩开关下保持不变：只换文字，不折叠结构 */
  position: relative;
  padding: var(--space-5);
  background: var(--color-bg-card);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-xs);
  margin-bottom: var(--space-3);
}

/* ==================== 顶部 ==================== */
.ov-top {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--space-2);
  min-height: 40px;
}
.ov-top-left {
  flex: 1;
  min-width: 0;
  display: flex;
  align-items: center;
  padding-top: 8px;
}
.ov-phase {
  font-size: var(--fs-h3);
  font-weight: 600;
  color: var(--color-text-primary);
}

.ov-icons {
  flex-shrink: 0;
  display: flex;
  gap: var(--space-2);
}
.ov-icon {
  /* 触控热区 40×40，图标 18px */
  width: 40px;
  height: 40px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: 0;
  background: transparent;
  padding: 0;
  border-radius: var(--radius-base);
  color: var(--color-text-tertiary);
  -webkit-tap-highlight-color: transparent;

  :deep(svg) { display: block; }
  &.is-on { color: var(--color-primary); }
  &:active { background: var(--color-bg-hover); }
}

.ov-day {
  margin-top: -6px;
  font-size: var(--fs-caption);
  color: var(--color-text-tertiary);
}

/* ==================== 进度条 ==================== */
.ov-bar {
  position: relative;
  height: 6px;
  margin: var(--space-4) 0 var(--space-3);
  border-radius: var(--radius-pill);
  background: var(--color-border-light);
}
.ov-bar-fill {
  height: 100%;
  border-radius: var(--radius-pill);
  transition: width var(--duration-base, 260ms) var(--ease-default);
}
.ov-bar-knob {
  position: absolute;
  top: 50%;
  width: 10px;
  height: 10px;
  margin-left: -5px;
  transform: translateY(-50%);
  border-radius: 50%;
  background: var(--color-bg-card);
  border: 2px solid var(--color-text-primary);
  box-sizing: border-box;
}

/* ==================== 主 / 副文案 ==================== */
.ov-main {
  margin: 0;
  font-size: var(--fs-metric);
  font-weight: 600;
  font-family: var(--font-num);
  font-variant-numeric: tabular-nums;
  color: var(--color-text-primary);
  line-height: 1.3;

  &.is-masked {
    font-family: inherit;
    letter-spacing: 2px;
    color: var(--color-text-disabled);
  }
}
.ov-sub {
  margin: 4px 0 0;
  font-size: var(--fs-caption);
  color: var(--color-text-tertiary);
  line-height: 1.45;

  &.is-masked {
    letter-spacing: 2px;
    color: var(--color-text-disabled);
  }
}

/* ==================== 数据不足的点 ==================== */
.ov-dots {
  display: flex;
  gap: 5px;
  margin-top: 10px;
}
.ov-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  border: 1.5px solid var(--color-border-strong);
  box-sizing: border-box;

  &.is-on {
    border-color: var(--color-primary);
    background: var(--color-primary);
  }
}

/* ==================== 低置信度引导链接 ==================== */
.ov-hint-link {
  display: inline-block;
  margin-top: 10px;
  padding: 0;
  border: 0;
  background: transparent;
  font-size: var(--fs-caption-sm);
  color: var(--color-primary);
  text-align: left;

  &:active { opacity: 0.7; }
}

/* ==================== 易孕期胶囊 ==================== */
.ov-fertile {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  margin-top: var(--space-3);
  padding: 5px 10px;
  border: 0;
  border-radius: var(--radius-pill);
  background: var(--color-fertile-soft);
  color: var(--color-fertile-strong);
  font-size: var(--fs-caption-sm);
  font-weight: 500;

  :deep(svg) { display: block; }
  &:active { opacity: 0.85; }
}
</style>
