// life-assisitant-ui-desktop/src/pages/record/HabitSection.tsx
/**
 * HabitSection — 习惯 KPI + 热力图 + 表格。
 *
 * R32：分类 emoji 映射改查 category-dict（HABIT_CATEGORIES / getHabitCategory），
 *      移除本地 sport/diet/life/study 的 emoji+bg/fg 平行定义。
 * R2：状态筛选现在会在 setStatusFilter 后触发 refetch（此前只改状态不拉数据）。
 * R7：今日达成后打卡按钮禁用（此前文案变「已完成」但仍可点）。
 * S05/S06：连续天数徽章（StreakBadge）逐行展示 + KPI 区「最长连续」取代名不符实的 kpi-streak。
 * S07：里程碑 7/21/66/100/365（MilestoneRow）+ 奖牌令牌 --medal-*。
 * 移除所有 Semi 图标与裸 emoji 字面量（B08/B09）。
 */
import { useState, useEffect, useMemo } from 'react'
import {
  Card,
  Button,
  Tag,
  Table,
  Select,
  Skeleton,
  Tooltip,
  Modal,
  InputNumber,
} from '@douyinfe/semi-ui'
import type { ColumnProps } from '@douyinfe/semi-ui/lib/es/table'
import { Icon, ICONS, TINT_VARS } from '@/components/icon'
import { EmptyHint } from '@/components/EmptyState'
import ErrorState from '@/components/ErrorState'
import { useHabitStore } from '@/stores/habit'
import { habitApi } from '@/api/habit'
import { statsApi } from '@/api/stats'
import IconBox from '@/components/IconBox'
import { getIconMapping } from '@/utils/icon-map'
import { HABIT_CATEGORIES, getHabitCategory } from '@/utils/category-dict'
import HabitEditDrawer from '@/components/HabitEditDrawer'
import { HabitHeatmap } from './components/HabitHeatmap'
import { StreakBadge, MilestoneRow, streakUnit } from './components/StreakBadge'
import type {
  Habit,
  HabitStatus,
  CreateHabitReq,
  UpdateHabitReq,
  HabitHeatmapItem,
} from '@/api/types'

const habitFilterOptions = [
  { value: '', label: '全部' },
  { value: 'active', label: '活跃' },
  { value: 'archived', label: '已归档' },
]

const categoryFilterOptions = [
  { value: '', label: '全部分类' },
  ...HABIT_CATEGORIES.map((c) => ({ value: c.id, label: c.label })),
]

const frequencyLabel: Record<string, string> = { daily: '每日', weekly: '每周', monthly: '每月' }

export function HabitSection() {
  const habitStore = useHabitStore()
  const now = useMemo(() => new Date(), [])
  const [calYear, setCalYear] = useState(now.getFullYear())
  const [calMonth, setCalMonth] = useState(now.getMonth() + 1) // 1-12
  const [habitDrawerVisible, setHabitDrawerVisible] = useState(false)
  const [editingHabit, setEditingHabit] = useState<Habit | null>(null)
  const [habitSaving, setHabitSaving] = useState(false)
  const [heatmapData, setHeatmapData] = useState<HabitHeatmapItem[]>([])
  const [error, setError] = useState(false)
  const [checkInModal, setCheckInModal] = useState<{ visible: boolean; habitId: string; habitTitle: string }>({ visible: false, habitId: '', habitTitle: '' })
  const [checkInDuration, setCheckInDuration] = useState<number>(0)

  // Fetch heatmap data（按当前选中月份）
  useEffect(() => {
    const startDate = `${calYear}-${String(calMonth).padStart(2, '0')}-01`
    const daysInMonth = new Date(calYear, calMonth, 0).getDate()
    const endDate = `${calYear}-${String(calMonth).padStart(2, '0')}-${String(daysInMonth).padStart(2, '0')}`
    statsApi.habitStats({ start_date: startDate, end_date: endDate }).then((res) => {
      setHeatmapData(res.heatmap || [])
    }).catch(() => {
      setError(true)
    })
  }, [calYear, calMonth, habitStore.items.length])

  // 习惯列表探错（record/index 已在 mount 时 fetchList，但 store 会静默吞错）
  useEffect(() => {
    let alive = true
    habitApi
      .list({})
      .then(() => { if (alive) setError(false) })
      .catch(() => { if (alive) setError(true) })
    return () => { alive = false }
  }, [])

  // 全站「最长连续」KPI（取活跃习惯里 longest_streak 最大值）
  const bestStreak = useMemo(() =>
    habitStore.items
      .filter((h) => h.status === 'active')
      .reduce((m, h) => Math.max(m, h.longest_streak ?? 0), 0),
    [habitStore.items]
  )

  function shiftMonth(delta: number) {
    let y = calYear
    let m = calMonth + delta
    if (m < 1) { m = 12; y -= 1 }
    if (m > 12) { m = 1; y += 1 }
    setCalYear(y)
    setCalMonth(m)
  }

  const isCurrentMonth = calYear === now.getFullYear() && calMonth === now.getMonth() + 1

  const habitColumns = useMemo<ColumnProps<Habit>[]>(() => [
    {
      title: '习惯',
      dataIndex: 'title',
      width: 260,
      render: (_v: any, record: Habit, _i: number) => {
        const habitIcon = record.icon ? getIconMapping(record.icon).icon : ICONS.HelpCircle
        const iconBg = record.color ? record.color + '22' : undefined
        return (
          <div className="col-habit" style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <IconBox icon={habitIcon} bg={iconBg} fg={record.color || undefined} size={32} iconSize={16} />
            <div className="habit-text" style={{ minWidth: 0 }}>
              <div className="habit-title" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{record.title}</div>
              {record.description ? <div className="habit-desc" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: 'var(--color-text-tertiary)', fontSize: 12 }}>{record.description}</div> : null}
            </div>
          </div>
        )
      },
    },
    {
      title: '分类',
      dataIndex: 'category',
      width: 110,
      render: (v: string) => {
        const c = getHabitCategory(v)
        if (!c) return <span style={{ color: 'var(--color-text-tertiary)' }}>{v || '—'}</span>
        return (
          <Tag style={{ background: TINT_VARS[c.tint].bg, color: TINT_VARS[c.tint].fg, border: 'none', fontSize: 12 }}>
            <Icon name={c.icon} size={14} style={{ marginRight: 4, verticalAlign: '-2px' }} />
            {c.label}
          </Tag>
        )
      },
    },
    {
      title: '频率',
      dataIndex: 'frequency',
      width: 80,
      render: (v: string) => (
        <span style={{ color: 'var(--color-text-secondary)' }}>{frequencyLabel[v] ?? v}</span>
      ),
    },
    {
      title: '目标',
      dataIndex: 'target_count',
      width: 100,
      render: (_v: any, r: Habit, _i: number) => `${r.target_count} ${r.unit}`,
    },
    {
      title: '今日进度',
      dataIndex: 'today_count',
      width: 170,
      render: (_v: any, r: Habit, _i: number) => {
        const done = r.today_count ?? 0
        const total = r.target_count
        const pct = total > 0 ? Math.min(100, Math.round((done / total) * 100)) : 0
        const finished = !!(r.today_done ?? r.today_completed)
        return (
          <div className="col-progress">
            <div className="progress-text">
              <span style={{ fontWeight: 600, color: finished ? 'var(--color-success-dark)' : 'var(--color-text-primary)' }}>
                {done}
              </span>
              <span className="muted">/ {total}</span>
              {finished ? (
                <Tag style={{ marginLeft: 8, background: 'var(--color-success-light)', color: 'var(--color-success-dark)', border: 'none' }}>
                  <Icon name="CheckSquare" size={12} style={{ marginRight: 2, verticalAlign: '-2px' }} /> 已达成
                </Tag>
              ) : null}
            </div>
            <div className="progress-bar">
              <div
                className="progress-fill"
                style={{ width: pct + '%', background: finished ? 'var(--color-success)' : r.color }}
              />
            </div>
          </div>
        )
      },
    },
    {
      title: '连续',
      dataIndex: 'current_streak',
      width: 110,
      render: (_v: any, r: Habit, _i: number) => (
        <StreakBadge streak={r.current_streak ?? 0} unit={streakUnit(r.frequency)} />
      ),
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 90,
      render: (s: HabitStatus) => (
        <Tag style={{
          background: s === 'active' ? 'var(--color-success-light)' : 'var(--color-bg-hover)',
          color: s === 'active' ? 'var(--color-success-dark)' : 'var(--color-text-tertiary)',
          border: 'none',
        }}>{s === 'active' ? '活跃' : '已归档'}</Tag>
      ),
    },
    {
      title: '操作',
      dataIndex: 'actions',
      width: 160,
      render: (_v: any, record: Habit, _i: number) => {
        const done = !!(record.today_done ?? record.today_completed)
        return (
          <div className="col-actions">
            <Tooltip content={done ? '今日已完成' : '打卡'}>
              <Button
                theme="borderless"
                type="primary"
                size="small"
                icon={<Icon name="CheckSquare" size={16} />}
                disabled={record.status !== 'active' || done}
                onClick={() => setCheckInModal({ visible: true, habitId: record.id, habitTitle: record.title })}
              >{done ? '已完成' : '打卡'}</Button>
            </Tooltip>
            <Tooltip content="编辑">
              <Button theme="borderless" type="tertiary" size="small" icon={<Icon name="Pencil" size={16} />} onClick={() => openEditHabit(record)} />
            </Tooltip>
            <Tooltip content="删除">
              <Button theme="borderless" type="danger" size="small" icon={<Icon name="X" size={16} />} onClick={() => onDeleteHabit(record)} />
            </Tooltip>
          </div>
        )
      },
    },
  ], [])

  function openEditHabit(h: Habit) {
    setEditingHabit(h)
    setHabitDrawerVisible(true)
  }

  function openCreateHabit() {
    setEditingHabit(null)
    setHabitDrawerVisible(true)
  }

  async function onHabitDrawerSubmit(data: CreateHabitReq | UpdateHabitReq) {
    setHabitSaving(true)
    try {
      if (editingHabit) {
        const ok = await habitStore.update(editingHabit.id, data as UpdateHabitReq)
        if (ok) setHabitDrawerVisible(false)
      } else {
        const created = await habitStore.create(data as CreateHabitReq)
        if (created) setHabitDrawerVisible(false)
      }
    } finally {
      setHabitSaving(false)
    }
  }

  function onDeleteHabit(h: Habit) {
    Modal.confirm({
      title: '删除习惯',
      content: `确认删除「${h.title}」？此操作可在 30 天内恢复。`,
      okText: '删除',
      okButtonProps: { type: 'danger', theme: 'solid' },
      cancelText: '取消',
      onOk: async () => {
        await habitStore.remove(h.id)
      },
    })
  }

  const filteredItems = habitStore.items.filter((h) => {
    if (habitStore.categoryFilter && h.category !== habitStore.categoryFilter) return false
    return true
  })

  const showError = error && !habitStore.loading && filteredItems.length === 0

  return (
    <Card bordered={false} className="card">
      <div className="card-head">
        <span className="card-title"><Icon name="ListChecks" size={16} style={{ marginRight: 6 }} />习惯追踪</span>
        <span className="card-sub">坚持就是力量</span>
      </div>

      <div className="kpi-row">
        <div className="kpi-card kpi-today">
          <div className="kpi-label">今日完成</div>
          <div className="kpi-value">{habitStore.todayDone}/{habitStore.todayTotal}</div>
          <div className="kpi-foot">
            <div className="kpi-bar">
              <div className="kpi-bar-fill" style={{
                width: habitStore.todayTotal > 0 ? Math.round((habitStore.todayDone / habitStore.todayTotal) * 100) + '%' : '0%',
                background: 'var(--color-success)',
              }} />
            </div>
            <span className="kpi-foot-text">
              {habitStore.todayTotal > 0 ? Math.round((habitStore.todayDone / habitStore.todayTotal) * 100) + '%' : '—'}
            </span>
          </div>
        </div>
        <div className="kpi-card kpi-streak">
          <div className="kpi-label">最长连续</div>
          <div className="kpi-value" style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <Icon name="Flame" size={22} style={{ color: 'var(--color-warning)' }} />
            {bestStreak}
          </div>
          <div className="kpi-foot"><span className="kpi-foot-text muted">天 · 历史最佳</span></div>
        </div>
        <div className="kpi-card kpi-month">
          <div className="kpi-label">今日打卡</div>
          <div className="kpi-value">{habitStore.todayCheckIns}</div>
          <div className="kpi-foot"><span className="kpi-foot-text muted">次</span></div>
        </div>
        <div className="kpi-card kpi-total">
          <div className="kpi-label">总习惯数</div>
          <div className="kpi-value">{habitStore.total}</div>
          <div className="kpi-foot"><span className="kpi-foot-text muted">含已归档</span></div>
        </div>
      </div>

      {/* 里程碑（S07） */}
      <div className="milestone-section">
        <span className="card-sub" style={{ marginRight: 12 }}>里程碑</span>
        <MilestoneRow longestStreak={bestStreak} />
      </div>

      {/* Habit Heatmap */}
      {heatmapData.length > 0 && (
        <div style={{ marginTop: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
            <span style={{ fontSize: 13, color: 'var(--color-text-secondary)' }}>{calYear}年{calMonth}月打卡日历</span>
            <Button theme="borderless" type="tertiary" size="small" onClick={() => shiftMonth(-1)}>‹</Button>
            <Button theme="borderless" type="tertiary" size="small" onClick={() => shiftMonth(1)}>›</Button>
            {!isCurrentMonth && (
              <Button theme="borderless" type="secondary" size="small" onClick={() => { setCalYear(now.getFullYear()); setCalMonth(now.getMonth() + 1) }}>回到本月</Button>
            )}
          </div>
          <HabitHeatmap data={heatmapData} year={calYear} month={calMonth} />
        </div>
      )}

      <div className="toolbar">
        <div className="toolbar-left">
          <Select value={habitStore.statusFilter as any} optionList={habitFilterOptions as any} onChange={(v: any) => { habitStore.setStatusFilter(v); habitStore.fetchList() }} style={{ width: 140 }} />
          <Select value={habitStore.categoryFilter as any} optionList={categoryFilterOptions as any} onChange={(v: any) => habitStore.setCategoryFilter(v)} style={{ width: 150 }} />
        </div>
        <div className="toolbar-right">
          <Button theme="solid" type="secondary" size="small" icon={<Icon name="PlusCircle" size={16} />} onClick={openCreateHabit}>新建习惯</Button>
          <Button theme="borderless" type="tertiary" icon={<Icon name="RefreshCw" size={16} />} onClick={() => habitStore.fetchList()} loading={habitStore.loading}>刷新</Button>
        </div>
      </div>

      {habitStore.loading && filteredItems.length === 0 ? (
        <div className="skeleton-wrap"><Skeleton><Skeleton.Paragraph rows={3} /></Skeleton></div>
      ) : showError ? (
        <ErrorState compact message="习惯加载失败，请重试" onRetry={() => { setError(false); habitStore.fetchList() }} />
      ) : filteredItems.length > 0 ? (
        <Table columns={habitColumns as any} dataSource={filteredItems} pagination={false} loading={habitStore.loading} rowKey="id" size="middle" className="habit-table" />
      ) : (
        <EmptyHint icon="FolderOpen" title="还没有习惯" desc="点击「新建习惯」开始" />
      )}

      <HabitEditDrawer visible={habitDrawerVisible} habit={editingHabit} saving={habitSaving} onClose={() => setHabitDrawerVisible(false)} onSubmit={onHabitDrawerSubmit} />

      {/* 打卡弹窗 */}
      <Modal
        title="打卡"
        visible={checkInModal.visible}
        onCancel={() => { setCheckInModal({ visible: false, habitId: '', habitTitle: '' }); setCheckInDuration(0) }}
        onOk={() => {
          habitStore.checkIn(checkInModal.habitId, { duration_minutes: checkInDuration > 0 ? checkInDuration : undefined })
          setCheckInModal({ visible: false, habitId: '', habitTitle: '' })
          setCheckInDuration(0)
        }}
        okText="确认打卡"
        cancelText="取消"
      >
        <div style={{ padding: '12px 0' }}>
          <div style={{ marginBottom: 12, fontSize: 14, fontWeight: 600 }}>
            「{checkInModal.habitTitle}」
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontSize: 13, color: 'var(--color-text-secondary)' }}>打卡时长（分钟）：</span>
            <InputNumber
              value={checkInDuration}
              onChange={(v: number | string | undefined) => setCheckInDuration(typeof v === 'number' ? v : parseInt(String(v ?? 0), 10) || 0)}
              min={0}
              max={1440}
              style={{ width: 100 }}
              placeholder="0"
            />
            <span style={{ fontSize: 12, color: 'var(--color-text-tertiary)' }}>留空或填 0 表示不记录时长</span>
          </div>
        </div>
      </Modal>
    </Card>
  )
}

export default HabitSection

// life-assisitant-ui-mobile/src/components/HabitSection.vue
<script setup lang="ts">
/**
 * HabitSection —— 记录页「习惯追踪」区块（移动端）
 *
 * SYNC-FROM-DESKTOP: life-assisitant-ui-desktop/src/pages/record/HabitSection.tsx
 * SYNC-FROM-BACKEND: life-assisitant-api/internal/model/dto/habit.go
 *                    life-assisitant-api/internal/controller/stats.go（热力图数据源）
 * 最后同步：2026-09-18（Phase 3.2 / 3.3）
 *
 * 与桌面端逐项对应：
 *   4 KPI（今日完成 / 最长连续 / 今日打卡 / 总习惯数）
 *   里程碑 7/21/66/100/365  → <MilestoneRow>
 *   月历热力图（chinese-days 农历/节气/节假日/调休）→ <HabitHeatmap>
 *   状态 + 分类筛选（分类为客户端过滤）
 *   逐行连续徽章 → <StreakBadge>
 *   打卡弹窗（可选时长，与桌面端同款交互）
 *
 * 移动端差异（交互层，业务语义不变）：
 *   - 表格 → 卡片列表（左滑编辑/删除，点击卡片编辑）
 *   - 筛选下拉 → van-dropdown-menu
 *   - 新建/编辑弹层由父级（记录页）持有，本组件只 emit 意图
 *
 * 热力图数据源：`GET /stats/habits?start_date&end_date`
 *   后端 service 中 start_date+end_date 同时存在时**优先于** range，
 *   故按月取数不需要传 range（与桌面端一致）。
 */
import { computed, onMounted, ref, watch } from 'vue'
import { statsApi } from '@/api/stats'
import { useHabitStore } from '@/stores/habit'
import { HABIT_CATEGORIES, getHabitCategory } from '@/utils/category-dict'
import { getIconMapping } from '@/utils/icon-map'
import Icon from '@/components/icon/Icon.vue'
import { todayDate } from '@/utils/date'
import HabitHeatmap from '@/components/HabitHeatmap.vue'
import MilestoneRow from '@/components/MilestoneRow.vue'
import StreakBadge from '@/components/StreakBadge.vue'
import type { Habit, HabitCategory, HabitHeatmapItem, HabitStatus } from '@/api/types'

const emit = defineEmits<{
  (e: 'create'): void
  (e: 'edit', habit: Habit): void
  (e: 'delete', habit: Habit): void
}>()

const habitStore = useHabitStore()

// ==================== 日期 / 日历 ====================
const now = new Date()
const calYear = ref(now.getFullYear())
const calMonth = ref(now.getMonth() + 1) // 1-12
const isCurrentMonth = computed(
  () => calYear.value === now.getFullYear() && calMonth.value === now.getMonth() + 1
)

/** 频率 → streak 单位（04 §2.2，与桌面端 streakUnit 一致） */
function streakUnit(frequency: string | undefined): string {
  if (frequency === 'weekly') return '周'
  if (frequency === 'monthly') return '月'
  return '天'
}

/** 频率中文 */
function frequencyLabel(f: string | undefined): string {
  const map: Record<string, string> = { daily: '每日', weekly: '每周', monthly: '每月' }
  return f ? (map[f] ?? f) : '—'
}

// ==================== 热力图 ====================
const heatmapData = ref<HabitHeatmapItem[]>([])
const heatmapLoading = ref(false)
const heatmapFailed = ref(false)

async function fetchHeatmap(): Promise<void> {
  const mm = String(calMonth.value).padStart(2, '0')
  const daysInMonth = new Date(calYear.value, calMonth.value, 0).getDate()
  const startDate = `${calYear.value}-${mm}-01`
  const endDate = `${calYear.value}-${mm}-${String(daysInMonth).padStart(2, '0')}`
  heatmapLoading.value = true
  heatmapFailed.value = false
  try {
    const res = await statsApi.habitStats({ start_date: startDate, end_date: endDate })
    heatmapData.value = res.heatmap ?? []
  } catch (e) {
    heatmapData.value = []
    heatmapFailed.value = true
    // eslint-disable-next-line no-console
    console.error('[HabitSection] fetchHeatmap failed', e)
  } finally {
    heatmapLoading.value = false
  }
}

function shiftMonth(delta: number): void {
  let y = calYear.value
  let m = calMonth.value + delta
  if (m < 1) {
    m = 12
    y -= 1
  }
  if (m > 12) {
    m = 1
    y += 1
  }
  calYear.value = y
  calMonth.value = m
}

function backToCurrentMonth(): void {
  calYear.value = now.getFullYear()
  calMonth.value = now.getMonth() + 1
}

// ==================== 筛选 ====================
const STATUS_FILTERS: Array<{ text: string; value: HabitStatus | '' }> = [
  { text: '全部', value: '' },
  { text: '活跃', value: 'active' },
  { text: '已归档', value: 'archived' },
]
const CATEGORY_FILTERS: Array<{ text: string; value: HabitCategory | '' }> = [
  { text: '全部分类', value: '' },
  ...HABIT_CATEGORIES.map((c) => ({ text: c.label, value: c.id as HabitCategory })),
]

const statusIndex = ref(0)
const categoryIndex = ref(0)

async function onStatusChange(index: number | string): Promise<void> {
  const i = Number(index)
  habitStore.setStatusFilter(STATUS_FILTERS[i]?.value ?? '')
  await habitStore.fetchHabits()
}

function onCategoryChange(index: number | string): void {
  const i = Number(index)
  habitStore.setCategoryFilter(CATEGORY_FILTERS[i]?.value ?? '')
}

// ==================== 打卡 ====================
const checkInShow = ref(false)
const checkInTarget = ref<Habit | null>(null)
const checkInDuration = ref<number>(0)

function openCheckIn(h: Habit): void {
  if (h.status !== 'active') return
  if (h.today_done ?? h.today_completed) return
  checkInTarget.value = h
  checkInDuration.value = 0
  checkInShow.value = true
}

async function confirmCheckIn(): Promise<void> {
  const h = checkInTarget.value
  if (!h) return
  const minutes = Number(checkInDuration.value) || 0
  checkInShow.value = false
  await habitStore.logHabit(h.id, {
    date: todayDate(),
    count: 1,
    ...(minutes > 0 ? { duration_minutes: minutes } : {}),
  })
  // 打卡会改变 streak，热力图随之刷新
  await fetchHeatmap()
}

// ==================== 列表渲染辅助 ====================
const filteredItems = computed(() => habitStore.filteredHabits)

/** 既无列表又加载失败 → 错误态；store 静默吞错，这里用「空 + 非加载」判定 */
const showEmpty = computed(() => !habitStore.loading && filteredItems.value.length === 0)

function habitProgressPct(h: Habit): number {
  if (!h.target_count) return 0
  return Math.min(100, Math.round(((h.today_count ?? 0) / h.target_count) * 100))
}

function isDone(h: Habit): boolean {
  return !!(h.today_done ?? h.today_completed)
}

/** 习惯图标（数据驱动：后端 h.icon 是 emoji，渲染层走字典取 Lucide 图标 + 语义色） */
function habitIcon(h: Habit) {
  // 空 icon 直接走 getIconMapping 内置兜底（HelpCircle + 中性色），不引入 emoji 字面量
  return getIconMapping(h.icon || '')
}

// ==================== 生命周期 ====================
onMounted(async () => {
  await Promise.all([habitStore.fetchHabits(), fetchHeatmap()])
})

// 日历月份变化 → 重新取热力图
watch([calYear, calMonth], () => {
  void fetchHeatmap()
})

// 习惯增删改后（列表长度变化）热力图可能变化，与桌面端依赖项保持一致
watch(
  () => habitStore.habits.length,
  () => {
    void fetchHeatmap()
  }
)

defineExpose({
  refresh: async () => {
    await Promise.all([habitStore.fetchHabits(), fetchHeatmap()])
  },
  openCheckIn,
})
</script>

<template>
  <section class="card habit-section">
    <div class="card-head">
      <h3 class="card-title">习惯追踪</h3>
      <span class="card-sub">坚持就是力量</span>
    </div>

    <!-- ============ 4 KPI ============ -->
    <div class="kpi-grid">
      <!-- KPI1 今日完成 -->
      <div class="kpi-card">
        <div class="kpi-label">今日完成</div>
        <div class="kpi-value">
          <span class="kv-strong">{{ habitStore.todayDone }}</span>
          <span class="kv-thin">/{{ habitStore.todayTotal }}</span>
        </div>
        <div class="kpi-bar">
          <div
            class="kpi-bar-fill"
            :style="{
              width: habitStore.todayTotal > 0
                ? Math.round((habitStore.todayDone / habitStore.todayTotal) * 100) + '%'
                : '0%',
            }"
          />
        </div>
        <div class="kpi-foot">
          {{ habitStore.todayTotal > 0
            ? Math.round((habitStore.todayDone / habitStore.todayTotal) * 100) + '%'
            : '—' }}
        </div>
      </div>

      <!-- KPI2 最长连续 -->
      <div class="kpi-card">
        <div class="kpi-label">最长连续</div>
        <div class="kpi-value">
          <Icon class="kv-flame" name="Flame" :size="16" :style="{ color: 'var(--tint-warning-fg)' }" aria-hidden="true" />
          <span class="kv-strong">{{ habitStore.bestStreak }}</span>
        </div>
        <div class="kpi-foot">天 · 历史最佳</div>
      </div>

      <!-- KPI3 今日打卡 -->
      <div class="kpi-card">
        <div class="kpi-label">今日打卡</div>
        <div class="kpi-value">
          <span class="kv-strong">{{ habitStore.todayCheckIns }}</span>
        </div>
        <div class="kpi-foot">次</div>
      </div>

      <!-- KPI4 总习惯数 -->
      <div class="kpi-card">
        <div class="kpi-label">总习惯数</div>
        <div class="kpi-value">
          <span class="kv-strong">{{ habitStore.total }}</span>
        </div>
        <div class="kpi-foot">含已归档</div>
      </div>
    </div>

    <!-- ============ 里程碑（7/21/66/100/365）============ -->
    <div class="milestone-section">
      <span class="section-label">里程碑</span>
      <MilestoneRow :longest-streak="habitStore.bestStreak" />
    </div>

    <!-- ============ 月历热力图 ============ -->
    <div class="heatmap-section">
      <div class="heatmap-head">
        <span class="heatmap-title">{{ calYear }}年{{ calMonth }}月打卡日历</span>
        <div class="heatmap-nav">
          <button type="button" class="nav-btn" aria-label="上个月" @click="shiftMonth(-1)">‹</button>
          <button type="button" class="nav-btn" aria-label="下个月" @click="shiftMonth(1)">›</button>
          <button
            v-if="!isCurrentMonth"
            type="button"
            class="nav-btn is-text"
            @click="backToCurrentMonth"
          >
            回到本月
          </button>
        </div>
      </div>

      <div v-if="heatmapLoading && heatmapData.length === 0" class="heatmap-skeleton">
        <div v-for="i in 5" :key="i" class="skel-bar" />
      </div>
      <div v-else-if="heatmapFailed && heatmapData.length === 0" class="heatmap-error">
        <span>打卡日历加载失败</span>
        <button type="button" class="heatmap-retry" @click="fetchHeatmap">重试</button>
      </div>
      <HabitHeatmap v-else-if="heatmapData.length > 0" :data="heatmapData" :year="calYear" :month="calMonth" />
      <div v-else class="heatmap-empty">本月还没有打卡记录</div>
    </div>

    <!-- ============ 筛选 ============ -->
    <van-dropdown-menu class="habit-filter" :overlay="false">
      <van-dropdown-item
        v-model="statusIndex"
        :options="STATUS_FILTERS"
        @change="onStatusChange"
      />
      <van-dropdown-item
        v-model="categoryIndex"
        :options="CATEGORY_FILTERS"
        @change="onCategoryChange"
      />
    </van-dropdown-menu>

    <div class="toolbar-right">
      <button type="button" class="btn-ghost" :disabled="habitStore.loading" @click="habitStore.fetchHabits()">
        <span aria-hidden="true">⟳</span> 刷新
      </button>
      <button type="button" class="btn-solid" @click="emit('create')">
        <span aria-hidden="true">＋</span> 新建习惯
      </button>
    </div>

    <!-- ============ 列表 ============ -->
    <div v-if="habitStore.loading && filteredItems.length === 0" class="loading-skeleton">
      <div v-for="i in 3" :key="i" class="skel-row" />
    </div>

    <div v-else-if="showEmpty" class="empty-state sm">
      <Icon class="empty-emoji" name="Sprout" :size="32" aria-hidden="true" />
      <h4 class="empty-title">还没有习惯</h4>
      <p class="empty-desc">点击「新建习惯」开始</p>
    </div>

    <ul v-else class="habit-list">
      <li v-for="h in filteredItems" :key="h.id" class="habit-swipe">
        <van-swipe-cell>
          <div class="habit-row" @click="emit('edit', h)">
            <Icon
              class="habit-emoji"
              :name="habitIcon(h).icon"
              :size="16"
              :style="{ background: (h.color || '#014DB2') + '22', color: habitIcon(h).vars.fg }"
            />

            <div class="habit-body">
              <div class="habit-title">{{ h.title }}</div>
              <div class="habit-sub">
                <span>{{ frequencyLabel(h.frequency) }}</span>
                <span class="dot">·</span>
                <span>目标 {{ h.target_count }} {{ h.unit || '次' }}</span>
                <template v-if="h.category">
                  <span class="dot">·</span>
                  <span
                    class="cat-tag"
                    :style="{
                      background: getHabitCategory(h.category)?.vars.bg,
                      color: getHabitCategory(h.category)?.vars.fg,
                    }"
                  >
                    <!-- 分类可能不在字典里（后端出现新枚举），图标兜底为 Pin -->
                    <Icon :name="getHabitCategory(h.category)?.icon ?? 'Pin'" :size="14" />
                    {{ getHabitCategory(h.category)?.label }}
                  </span>
                </template>
              </div>

              <!-- 进度条 + 连续徽章 -->
              <div class="habit-meta">
                <div class="mini-bar">
                  <div
                    class="mini-bar-fill"
                    :style="{
                      width: habitProgressPct(h) + '%',
                      background: isDone(h) ? 'var(--color-success)' : (h.color || 'var(--color-primary)'),
                    }"
                  />
                </div>
                <StreakBadge :streak="h.current_streak ?? 0" :unit="streakUnit(h.frequency)" />
                <span v-if="h.status === 'archived'" class="archived-tag">已归档</span>
              </div>
            </div>

            <button
              type="button"
              class="check-btn"
              :class="{ 'is-done': isDone(h), 'has-progress': (h.today_count ?? 0) > 0 && !isDone(h) }"
              :disabled="h.status !== 'active' || isDone(h)"
              @click.stop="openCheckIn(h)"
            >
              <template v-if="isDone(h)">
                <span class="check-tick">✓</span>
                <span class="check-text">已完成</span>
              </template>
              <template v-else>
                <span class="check-tick">+</span>
                <span class="check-text">{{ h.today_count ?? 0 }}/{{ h.target_count }}</span>
              </template>
            </button>
          </div>

          <!-- 左滑操作（B4：替代失效的 @contextmenu） -->
          <template #right>
            <div class="swipe-actions">
              <button type="button" class="swipe-btn is-edit" @click="emit('edit', h)">编辑</button>
              <button type="button" class="swipe-btn is-delete" @click="emit('delete', h)">删除</button>
            </div>
          </template>
        </van-swipe-cell>
      </li>
    </ul>

    <!-- ============ 打卡弹窗（可选时长，与桌面端一致）============
         ⚠️ teleport="body" 必留：本组件在记录页 main.tab-body（滚动容器）里，
         iOS 上会被布局层 chrome 压住。完整说明见 period/PeriodDaySheet.vue -->
    <van-popup v-model:show="checkInShow" position="bottom" round teleport="body">
      <div class="checkin-sheet">
        <h4 class="checkin-title">打卡</h4>
        <p class="checkin-sub">「{{ checkInTarget?.title }}」</p>

        <div class="checkin-field">
          <label class="checkin-label">打卡时长（分钟）</label>
          <van-stepper
            v-model="checkInDuration"
            :min="0"
            :max="1440"
            :step="5"
            theme="round"
            button-size="28"
          />
        </div>
        <p class="checkin-hint">留空或填 0 表示不记录时长</p>

        <div class="checkin-actions">
          <button type="button" class="btn-ghost is-wide" @click="checkInShow = false">取消</button>
          <button type="button" class="btn-solid is-wide" @click="confirmCheckIn">确认打卡</button>
        </div>
      </div>
    </van-popup>
  </section>
</template>

<style lang="scss" scoped>
.card {
  background: var(--color-bg-card);
  border-radius: 16px;
  box-shadow: var(--shadow-xs);
  padding: 16px;
  margin-bottom: 16px;
}
.card-head {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  margin-bottom: 12px;
}
.card-title {
  font-size: var(--fs-h4);
  font-weight: 600;
  color: var(--color-text-primary);
  margin: 0;
}
.card-sub {
  font-size: var(--fs-caption-sm);
  color: var(--color-text-tertiary);
}

/* ========== 4 KPI ========== */
.kpi-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 10px;
  margin-bottom: 14px;
}
.kpi-card {
  padding: 12px;
  background: var(--color-bg-hover);
  border-radius: 12px;
}
.kpi-label {
  font-size: var(--fs-caption-sm);
  color: var(--color-text-tertiary);
  margin-bottom: 4px;
}
.kpi-value {
  display: flex;
  align-items: baseline;
  gap: 3px;
}
.kv-strong {
  /* 数值阶令牌：与首页 / 待办 / 统计的 KPI 数值统一（原为 22px） */
  font-size: var(--fs-metric);
  font-weight: 700;
  color: var(--color-text-primary);
  font-family: var(--font-num);
  line-height: 1.15;
}
.kv-thin {
  /* 数值次要部分令牌：与首页 / 统计的数值次要部分统一 */
  font-size: var(--fs-metric-sm);
  color: var(--color-text-tertiary);
  font-family: var(--font-num);
}
.kv-flame { line-height: 1; }
.kpi-bar {
  height: 4px;
  margin: 6px 0 4px;
  background: var(--color-border-light);
  border-radius: 999px;
  overflow: hidden;
}
.kpi-bar-fill {
  height: 100%;
  background: var(--color-success);
  border-radius: 999px;
  transition: width var(--duration-normal) var(--ease-default);
}
.kpi-foot {
  font-size: var(--fs-micro);
  color: var(--color-text-tertiary);
}

/* ========== 里程碑 ========== */
.milestone-section {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 0 14px;
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
  &::-webkit-scrollbar { display: none; }
}
.section-label {
  flex-shrink: 0;
  font-size: var(--fs-caption);
  color: var(--color-text-tertiary);
}

/* ========== 热力图 ========== */
.heatmap-section {
  padding-bottom: 14px;
  border-bottom: 1px solid var(--color-border-light);
  margin-bottom: 8px;
}
.heatmap-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}
.heatmap-title {
  font-size: var(--fs-caption);
  color: var(--color-text-secondary);
}
.heatmap-nav {
  display: flex;
  align-items: center;
  gap: 6px;
}
.nav-btn {
  min-width: 26px;
  height: 26px;
  padding: 0 8px;
  font-size: var(--fs-body);
  color: var(--color-text-secondary);
  background: var(--color-bg-hover);
  border: 0;
  border-radius: 8px;
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  &:active { transform: scale(0.94); }
  &.is-text { font-size: var(--fs-caption-sm); color: var(--color-primary); }
}
.heatmap-skeleton {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.skel-bar {
  height: 26px;
  border-radius: 6px;
  background: linear-gradient(90deg, #F3F4F6 25%, #E5E7EB 50%, #F3F4F6 75%);
  background-size: 200% 100%;
  animation: shimmer 1.5s infinite;
}
.heatmap-error {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px;
  font-size: var(--fs-caption);
  color: var(--color-danger-dark);
  background: var(--color-danger-light);
  border-radius: 10px;
}
.heatmap-retry {
  padding: 4px 12px;
  font-size: var(--fs-caption-sm);
  font-weight: 600;
  color: #FFFFFF;
  background: var(--color-danger);
  border: 0;
  border-radius: 999px;
  cursor: pointer;
}
.heatmap-empty {
  padding: 20px;
  text-align: center;
  font-size: var(--fs-caption-sm);
  color: var(--color-text-tertiary);
}

/* ========== 筛选 / 工具栏 ========== */
.habit-filter {
  margin: 8px -16px 10px;
  :deep(.van-dropdown-menu__bar) {
    background: transparent;
    box-shadow: none;
  }
  :deep(.van-dropdown-menu__title) {
    font-size: var(--fs-caption);
    color: var(--color-text-secondary);
  }
}
.toolbar-right {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
  margin-bottom: 12px;
}
.btn-ghost,
.btn-solid {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  height: 30px;
  padding: 0 12px;
  font-size: var(--fs-caption-sm);
  font-weight: 500;
  border: 0;
  border-radius: 999px;
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  &:active { transform: scale(0.96); }
  &:disabled { opacity: 0.5; cursor: not-allowed; }
  &.is-wide { flex: 1; height: 42px; justify-content: center; font-size: var(--fs-body-sm); }
}
.btn-ghost {
  color: var(--color-text-secondary);
  background: var(--color-bg-hover);
}
.btn-solid {
  color: #FFFFFF;
  background: var(--color-primary);
}

/* ========== 列表 ========== */
.habit-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.habit-swipe {
  border-radius: 12px;
  box-shadow: var(--shadow-xs);
  overflow: hidden;
}
.habit-row {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  background: var(--color-bg-card);
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  &:active { background: var(--color-bg-hover); }
}
.habit-emoji {
  flex-shrink: 0;
  width: 38px;
  height: 38px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 10px;
  line-height: 1;
}
.habit-body { flex: 1; min-width: 0; }
.habit-title {
  font-size: var(--fs-body-sm);
  font-weight: 600;
  color: var(--color-text-primary);
  margin-bottom: 3px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.habit-sub {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: var(--fs-micro);
  color: var(--color-text-tertiary);
  overflow: hidden;
  white-space: nowrap;
}
.dot { opacity: 0.5; }
.cat-tag {
  padding: 1px 6px;
  font-size: var(--fs-tab);
  border-radius: 999px;
  white-space: nowrap;
}
.habit-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 6px;
}
.mini-bar {
  flex: 1;
  min-width: 40px;
  max-width: 90px;
  height: 4px;
  background: var(--color-border-light);
  border-radius: 999px;
  overflow: hidden;
}
.mini-bar-fill {
  height: 100%;
  border-radius: 999px;
  transition: width var(--duration-normal) var(--ease-default);
}
.archived-tag {
  font-size: var(--fs-tab);
  color: var(--color-text-tertiary);
  background: var(--color-bg-hover);
  padding: 1px 6px;
  border-radius: 999px;
}

.check-btn {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 7px 11px;
  font-size: var(--fs-caption-sm);
  font-weight: 600;
  background: var(--color-primary);
  color: #FFFFFF;
  border: 0;
  border-radius: 999px;
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  font-family: var(--font-num);
  &:active { transform: scale(0.94); }
  &.is-done { background: var(--color-success); }
  &.has-progress { background: var(--color-warning); }
  &:disabled { cursor: default; }
}
.check-tick { font-size: 13px; line-height: 1; }

.swipe-actions { display: flex; height: 100%; }
.swipe-btn {
  width: 68px;
  height: 100%;
  border: 0;
  padding: 0;
  font-size: var(--fs-body-sm);
  font-weight: 500;
  color: #FFFFFF;
  cursor: pointer;
  &:active { opacity: 0.85; }
  &.is-edit { background: var(--color-text-tertiary); }
  &.is-delete { background: var(--color-danger); }
}

/* ========== 打卡弹窗 ========== */
.checkin-sheet {
  padding: 20px 20px calc(20px + env(safe-area-inset-bottom, 0px));
}
.checkin-title {
  font-size: var(--fs-h4);
  font-weight: 600;
  color: var(--color-text-primary);
  margin: 0 0 4px;
}
.checkin-sub {
  font-size: var(--fs-caption);
  color: var(--color-text-secondary);
  margin: 0 0 16px;
}
.checkin-field {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}
.checkin-label {
  font-size: var(--fs-caption);
  color: var(--color-text-secondary);
}
.checkin-hint {
  font-size: var(--fs-micro);
  color: var(--color-text-tertiary);
  margin: 8px 0 18px;
}
.checkin-actions {
  display: flex;
  gap: 10px;
}

/* ========== 空 / 加载 ========== */
.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 48px 24px;
  text-align: center;
  &.sm { padding: 32px 24px; }
}
.empty-emoji { margin-bottom: 10px; opacity: 0.6; }
.empty-title {
  font-size: var(--fs-body);
  font-weight: 600;
  color: var(--color-text-primary);
  margin: 0 0 4px;
}
.empty-desc {
  font-size: var(--fs-caption-sm);
  color: var(--color-text-tertiary);
  margin: 0;
}
.loading-skeleton {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.skel-row {
  height: 64px;
  border-radius: 12px;
  background: linear-gradient(90deg, #F3F4F6 25%, #E5E7EB 50%, #F3F4F6 75%);
  background-size: 200% 100%;
  animation: shimmer 1.5s infinite;
}
@keyframes shimmer {
  0%   { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}
</style>
